"use client";
import { useState } from "react";
import { DEFAULT_QC, orderTotals, stageOf, type WorkOrder } from "../app-data";
import { Fact, now, num, uid, useApp } from "./store";

export const floorNav=["Production","Pack orders","My account"];
const RACK=24;

export function FloorView({nav,line,setLine}:{nav:string;line:string;setLine:(l:string)=>void}){
  const {data,commit,notify,openRecord}=useApp();
  const [unit,setUnit]=useState<"racks"|"bottles">("racks");const [amount,setAmount]=useState("1");const [hist,setHist]=useState<{k:"good"|"scrap";n:number}[]>([]);
  const operator=data.roles.find(r=>/warehouse|floor/i.test(r.name))?.members[0]||"Warehouse";
  if(nav==="Pack orders")return <PackOrders operator={operator}/>;
  const lines=data.settings.lines||["Line 1"];
  const lineWOs=data.workOrders.filter(w=>w.line===line&&w.status!=="Done");
  const job=lineWOs.find(w=>w.status==="Running")||lineWOs.find(w=>w.status==="Paused");
  const queue=lineWOs.filter(w=>w!==job&&["Released","Scheduled"].includes(w.status));
  const order=job?data.orders.find(o=>o.id===job.orderId):undefined;const customer=order?data.customers.find(c=>c.id===order.customerId):undefined;
  const patch=(id:string,fn:(w:WorkOrder)=>WorkOrder,action:string,summary:string,extra?:(v:typeof data)=>Partial<typeof data>)=>commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===id?fn(x):x),...(extra?extra(v):{})}),action,summary);
  const add=(n:number)=>{if(!job)return;const left=Math.max(0,job.quantity-job.good);const k=Math.min(n,left);if(!k)return notify("Nothing added — this work order is complete. Finish it.");
    patch(job.id,w=>({...w,good:w.good+k}),"production.report",`${k} good bottles added to ${job.id}`,v=>({inventory:v.inventory.map(row=>{const mat=v.itemRates.find(r=>r.item===job.item)?.material;return row.item===mat?{...row,onHand:Math.max(0,row.onHand-k)}:row}),activities:[{id:uid("a"),customerId:order?.customerId,title:"Production updated",detail:`${job.id} · ${num(k)} good bottles`,actor:operator,createdAt:now()},...v.activities]}));
    setHist(h=>[...h,{k:"good",n:k}]);notify(`${num(k)} bottles added — ${job.id}`)};
  const scrap=()=>{if(!job)return;patch(job.id,w=>({...w,scrap:w.scrap+1}),"production.scrap",`1 scrap on ${job.id}`);setHist(h=>[...h,{k:"scrap",n:1}])};
  const undo=()=>{if(!job||!hist.length)return;const h=hist[hist.length-1];patch(job.id,w=>h.k==="good"?{...w,good:Math.max(0,w.good-h.n)}:{...w,scrap:Math.max(0,w.scrap-h.n)},"production.undo",`undo on ${job.id}`);setHist(x=>x.slice(0,-1))};
  const pause=()=>{if(!job)return;const paused=job.status==="Paused";const reason=paused?null:window.prompt("What's the problem? (optional)","");patch(job.id,w=>({...w,status:paused?"Running":"Paused",qcNote:reason?`${w.qcNote?w.qcNote+" · ":""}Paused: ${reason}`:w.qcNote}),paused?"production.resume":"production.pause",`${job.id} ${paused?"resumed":"paused"}`);notify(paused?`${job.id} resumed`:`${job.id} paused — owner notified`)};
  const qcNote=()=>{if(!job)return;const n=window.prompt("Quality note for this run (what you saw, what you changed):",job.qcNote||"");if(n===null)return;patch(job.id,w=>({...w,qcNote:n}),"qc.note",`${job.id} floor note`);notify("Quality note saved — owner notified")};
  const finish=()=>{if(!job)return;const checks=(data.itemRates.find(r=>r.item===job.item)?.qcChecks||DEFAULT_QC).map(l=>({label:l,result:null as boolean|null}));
    patch(job.id,w=>({...w,status:"QC hold",qc:w.qc||checks}),"production.finish",`${job.id} finished`,v=>({orders:v.orders.map(o=>o.id===job.orderId&&stageOf(o)<2?{...o,stage:2,status:"Quality check"}:o),notices:[{id:uid("n"),title:`${job.id} finished — quality checks waiting`,detail:`${num(job.good)} good · ${job.scrap} scrap${customer?` · ${customer.name}`:""}`,urgent:true,read:false,createdAt:now(),target:"Quality"},...v.notices],activities:[{id:uid("a"),customerId:order?.customerId,title:"Run finished",detail:`${job.id} · ${num(job.good)} good · ${job.scrap} scrap`,actor:operator,createdAt:now()},...v.activities]}));
    setHist([]);notify(`Job finished — ${checks.length} quality checks now waiting for the owner`)};
  const start=(w:WorkOrder)=>{patch(w.id,x=>({...x,status:"Running"}),"wo.start",`${w.id} started`,v=>({orders:v.orders.map(o=>o.id===w.orderId&&stageOf(o)<1?{...o,stage:1,status:"In production"}:o)}));notify(`${w.id} started on ${line}`)};
  const pct=job?Math.min(100,Math.round(job.good/job.quantity*100)):0;const perRack=RACK;const amt=Math.max(0,Number(amount)||0)*(unit==="racks"?perRack:1);
  const clock=new Date().toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});
  return <>
    <div className="floor-heading"><div><p className="eyebrow">{job?`${job.status==="Paused"?"Paused":"Running now"} · ${line}`:`${line} · idle`}</p><h1>{job?job.item:"No job running"}</h1><p>{job?`${job.id}${customer?` · ${customer.name} · ${order?.id}`:` · ${job.purpose}`}`:"Start the next job below, or ask the owner to release one."}{order?.notes&&<><br/><b style={{color:"#cf6822"}}>Note from sales: {order.notes}</b></>}</p></div><div style={{textAlign:"right"}}><strong>{clock}</strong>{lines.length>1&&<div className="segmented" style={{marginTop:8}}>{lines.map(l=><button key={l} className={l===line?"active":""} onClick={()=>setLine(l)}>{l}</button>)}</div>}</div></div>
    {job&&<section className="floor-job">
      <div className="recipe"><Fact value={num(job.good)} label="Good bottles made"/><Fact value={num(job.quantity)} label="Bottles needed"/><Fact value={String(job.scrap)} label="Scrap"/><Fact value={String(Math.ceil(job.quantity/(data.itemRates.find(r=>r.item===job.item)?.unitsPerCase||2)))} label="Boxes to pack"/></div>
      <div className="progress"><span style={{width:`${pct}%`}}/></div><p className="progress-copy">{pct}% complete · {num(Math.max(0,job.quantity-job.good))} bottles remaining{job.qcNote?` · ${job.qcNote}`:""}</p>
      <div className="floor-actions" style={{marginBottom:12}}><button className="primary giant" disabled={job.status==="Paused"} onClick={()=>add(perRack)}>+ {perRack} good (one rack)</button><button className="secondary giant" disabled={job.status==="Paused"} onClick={scrap} style={{borderColor:"#c0392b",color:"#c0392b"}}>+ 1 scrap</button></div>
      <div className="entry-box"><h2>Add a different amount</h2><div className="segmented"><button className={unit==="racks"?"active":""} onClick={()=>setUnit("racks")}>Racks of {perRack}</button><button className={unit==="bottles"?"active":""} onClick={()=>setUnit("bottles")}>Individual bottles</button></div><label>{unit==="racks"?`How many racks? (${perRack} bottles each)`:"How many good bottles?"}<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="primary giant" disabled={job.status==="Paused"} onClick={()=>add(amt)}>Add {num(amt)} bottles</button></div>
      <div className="floor-actions"><button className="secondary" onClick={pause}>{job.status==="Paused"?"▶ Resume":"⏸ Pause / problem"}</button><button className="secondary" disabled={!hist.length} onClick={undo}>Undo last{hist.length?` (${hist[hist.length-1].k==="good"?"+"+hist[hist.length-1].n+" good":"+1 scrap"})`:""}</button><button className="secondary" onClick={qcNote}>Record quality note</button><button className="finish" onClick={finish}>Finish work order & send to quality</button></div>
    </section>}
    <section className="panel" style={{marginTop:18}}><div className="panel-title"><h2>Up next on {line}</h2></div>{queue.length?queue.map(w=>{const o=data.orders.find(o=>o.id===w.orderId);const c=o?data.customers.find(c=>c.id===o.customerId):undefined;return <div className="money-row" key={w.id}><span><b>{w.id} · {w.item} · {num(w.quantity)}</b><small>{c?`${c.name} · needed ${o?.due}`:w.purpose}{o?.notes?` · ${o.notes}`:""}</small></span>{w.status==="Released"&&!job?<button className="primary" onClick={()=>start(w)}>Start</button>:<button className="secondary" onClick={()=>openRecord(w.id)}>{w.status}</button>}</div>}):<p className="empty-list">Queue is empty.</p>}</section>
  </>;
}

export function PackOrders({operator}:{operator:string}){
  const {data,commit,notify}=useApp();
  const ready=data.orders.filter(o=>stageOf(o)===3||o.status==="Packed");
  const pack=(id:string)=>{commit(v=>({...v,orders:v.orders.map(o=>o.id===id?{...o,status:"Packed"}:o),workOrders:v.workOrders.map(w=>w.orderId===id?{...w,packed:w.good}:w),activities:[{id:uid("a"),customerId:v.orders.find(o=>o.id===id)?.customerId,title:"Order packed",detail:`${id} packed and labeled`,actor:operator,createdAt:now()},...v.activities]}),"packing.complete",`${id} packed`);notify(`${id} packed — owner and sales notified`)};
  const ship=(id:string)=>{commit(v=>{const o=v.orders.find(o=>o.id===id)!;const t=orderTotals(o,v);const c=v.customers.find(c=>c.id===o.customerId);return {...v,orders:v.orders.map(x=>x.id===id?{...x,stage:4,status:"Shipped"}:x),inventory:v.inventory.map(row=>{const l=t.lines.find(l=>l.item===row.item);return l?{...row,onHand:Math.max(0,row.onHand-l.quantity),committed:Math.max(0,row.committed-l.quantity)}:row}),notices:[{id:uid("n"),title:`${id} shipped`,detail:`${c?.name} · ready to invoice`,urgent:false,read:false,createdAt:now(),target:"Invoices"},...v.notices],activities:[{id:uid("a"),customerId:o.customerId,title:"Shipped",detail:`${id} left the building`,actor:operator,createdAt:now()},...v.activities]}},"order.ship",`${id} shipped`);notify(`${id} shipped — sales can send the invoice now`)};
  return <><div className="floor-heading"><div><p className="eyebrow">Packing queue</p><h1>Pack customer orders</h1><p>Exact quantities, boxes, and pallet instructions for each order.</p></div></div><div className="pack-grid">{ready.length?ready.map(order=>{const customer=data.customers.find(x=>x.id===order.customerId);const t=orderTotals(order,data);const sm=(data.settings.shipMethods||[]).find(s=>s.id===order.shipMethod);return <article className="pack-card" key={order.id}><p className="eyebrow">Order {order.id} · needed {order.due}</p><h2>{customer?.name}</h2><p>{t.lines.map(l=>`${num(l.quantity)} × ${l.item}`).join(" + ")}</p><div className="pack-facts"><Fact value={`${t.cases} boxes`} label="Total to pack"/><Fact value={`${num(order.quantity)} bottles`} label="Bottle quantity"/><Fact value={`${Math.max(1,Math.ceil(t.cases/48))} pallet${Math.ceil(t.cases/48)===1?"":"s"}`} label={sm?.name.split(" · ")[0]||"Pallet plan"}/></div>{order.notes&&<p style={{color:"#cf6822",fontWeight:700}}>Note from sales: {order.notes}</p>}<div className="pack-status">{order.status}</div>{order.status==="Packed"?<button className="primary giant" onClick={()=>ship(order.id)}>Mark shipped & notify team</button>:<button className="primary giant" onClick={()=>pack(order.id)}>Mark packed</button>}</article>}):<p className="empty-list" style={{color:"#B8BFBA"}}>Nothing is ready to pack. Orders show up here when quality passes.</p>}</div></>;
}
