"use client";
import { useState } from "react";
import { DEFAULT_QC, int, orderTotals, stageOf, type WorkOrder } from "../app-data";
import { Icon, nowLabel, uid, useStore } from "./ui";

const RACK=24;

// The floor app keeps its original jobs — count good bottles (by rack or one at a time), count scrap,
// pause, record a quality note, finish the run, pack orders — in the new look.
export function FloorApp({tab,line}:{tab:"production"|"pack";line:string}){
  const {data,commit,toast,go}=useStore();
  const [unit,setUnit]=useState<"racks"|"bottles">("racks");const [amount,setAmount]=useState("1");const [hist,setHist]=useState<{k:"good"|"scrap";n:number}[]>([]);
  const lineWOs=data.workOrders.filter(w=>w.line===line&&w.status!=="Done");
  const job=lineWOs.find(w=>w.status==="Running")||lineWOs.find(w=>w.status==="Paused");
  const nextUp=lineWOs.filter(w=>w!==job&&["Released","Scheduled","Needs scheduling"].includes(w.status));
  const order=job?data.orders.find(o=>o.id===job.orderId):undefined;const cust=order?data.customers.find(c=>c.id===order.customerId):undefined;
  const clock=new Date().toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"});
  const operator=data.roles.find(r=>/warehouse|floor/i.test(r.name))?.members[0]||"Floor";
  const patch=(id:string,fn:(w:WorkOrder)=>WorkOrder,action:string,summary:string,extra?:(v:typeof data)=>Partial<typeof data>)=>commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===id?fn(x):x),...(extra?extra(v):{})}),action,summary);

  const add=(n:number)=>{if(!job)return;const left=Math.max(0,job.quantity-job.good);const k=Math.min(n,left);if(!k){toast("Nothing added — this work order is complete. Finish it.");return}
    patch(job.id,w=>({...w,good:w.good+k}),"production.report",`${k} good added to ${job.id}`,v=>({inventory:v.inventory.map(row=>{const mat=v.itemRates.find(r=>r.item===job.item)?.material;return row.item===mat?{...row,onHand:Math.max(0,row.onHand-k)}:row}),activities:[{id:uid("a"),customerId:order?.customerId,title:"Production update",detail:`${job.id} · ${int(k)} good bottles`,actor:operator,createdAt:nowLabel()},...v.activities]}));
    setHist(h=>[...h,{k:"good",n:k}])};
  const scrap=()=>{if(!job)return;patch(job.id,w=>({...w,scrap:w.scrap+1}),"production.scrap",`1 scrap on ${job.id}`);setHist(h=>[...h,{k:"scrap",n:1}])};
  const undo=()=>{if(!job||!hist.length)return;const h=hist[hist.length-1];patch(job.id,w=>h.k==="good"?{...w,good:Math.max(0,w.good-h.n)}:{...w,scrap:Math.max(0,w.scrap-h.n)},"production.undo",`undo on ${job.id}`);setHist(x=>x.slice(0,-1))};
  const pause=()=>{if(!job)return;const paused=job.status==="Paused";const reason=paused?null:window.prompt("What's the problem? (optional)","");patch(job.id,w=>({...w,status:paused?"Running":"Paused",qcNote:reason?`${w.qcNote?w.qcNote+" · ":""}Paused: ${reason}`:w.qcNote}),paused?"production.resume":"production.pause",`${job.id} ${paused?"resumed":"paused"}`)};
  const qcNote=()=>{if(!job)return;const n=window.prompt("Quality note for this run (what you saw, what you changed):",job.qcNote||"");if(n===null)return;patch(job.id,w=>({...w,qcNote:n}),"qc.note",`${job.id} floor note`);toast("Note saved for Chris.")};
  const finish=()=>{if(!job)return;const checks=(data.itemRates.find(r=>r.item===job.item)?.qcChecks||DEFAULT_QC).map(l=>({label:l,result:null as boolean|null}));
    patch(job.id,w=>({...w,status:"QC hold",qc:w.qc||checks}),"production.finish",`${job.id} finished`,v=>({orders:v.orders.map(o=>o.id===job.orderId&&stageOf(o)<2?{...o,stage:2,status:"Quality check"}:o),notices:[{id:uid("n"),title:`${job.id} finished — quality checks waiting`,detail:`${int(job.good)} good · ${job.scrap} scrap${cust?` · ${cust.name}`:""}`,urgent:true,read:false,createdAt:nowLabel(),target:"Quality"},...v.notices]}));
    setHist([]);toast(`${job.id} finished — ${checks.length} quality checks now waiting for Chris.`)};
  const start=(w:WorkOrder)=>{patch(w.id,x=>({...x,status:"Running"}),"wo.start",`${w.id} started`,v=>({orders:v.orders.map(o=>o.id===w.orderId&&stageOf(o)<1?{...o,stage:1,status:"In production"}:o)}));toast(`${w.id} started on ${line}.`)};

  const header=<div className="fbar"><b><i></i>{line} · Blow molder</b>{job?<span className={`live ${job.status==="Paused"?"paused":""}`}><i></i>{job.status==="Paused"?"Paused":"Running"}</span>:<span className="live" style={{color:"#B8BFBA"}}><i style={{background:"#B8BFBA"}}></i>Idle</span>}<span style={{color:"#B8BFBA"}}>{operator} · {clock}</span></div>;
  const tabs=<div className="tabs"><button className={tab==="production"?"on":""} onClick={()=>go("warehouse")}>Production</button><button className={tab==="pack"?"on":""} onClick={()=>go("warehouse/pack")}>Pack orders {data.orders.filter(o=>stageOf(o)===3).length?`(${data.orders.filter(o=>stageOf(o)===3).length})`:""}</button></div>;

  if(tab==="pack"){
    const ready=data.orders.filter(o=>stageOf(o)===3||o.status==="Packed");
    const pack=(id:string)=>{commit(v=>({...v,orders:v.orders.map(o=>o.id===id?{...o,status:"Packed"}:o),workOrders:v.workOrders.map(w=>w.orderId===id?{...w,packed:w.good}:w),activities:[{id:uid("a"),customerId:v.orders.find(o=>o.id===id)?.customerId,title:"Order packed",detail:`${id} packed and labeled`,actor:operator,createdAt:nowLabel()},...v.activities]}),"packing.complete",`${id} packed`);toast(`${id} packed.`)};
    const ship=(id:string)=>{commit(v=>{const o=v.orders.find(o=>o.id===id)!;const t=orderTotals(o,v);return {...v,orders:v.orders.map(x=>x.id===id?{...x,stage:4,status:"Shipped"}:x),inventory:v.inventory.map(row=>{const l=t.lines.find(l=>l.item===row.item);return l?{...row,onHand:Math.max(0,row.onHand-l.quantity),committed:Math.max(0,row.committed-l.quantity)}:row}),notices:[{id:uid("n"),title:`${id} shipped`,detail:`${v.customers.find(c=>c.id===o.customerId)?.name} · ready to invoice`,urgent:false,read:false,createdAt:nowLabel(),target:"Money"},...v.notices],activities:[{id:uid("a"),customerId:o.customerId,title:"Shipped",detail:`${id} left the building`,actor:operator,createdAt:nowLabel()},...v.activities]}},"order.ship",`${id} shipped`);toast(`${id} shipped — sales can send the invoice now.`)};
    return <div className="fl">{header}{tabs}<div><div className="k" style={{marginBottom:10}}>Orders ready to pack and ship</div><div className="pack">{ready.length?ready.map(o=>{const c=data.customers.find(c=>c.id===o.customerId);const t=orderTotals(o,data);const sm=(data.settings.shipMethods||[]).find(s=>s.id===o.shipMethod);return <div key={o.id} className="pcard"><div className="k">{o.id} · needed {o.due}</div><div className="v">{c?.name}</div><div style={{color:"#B8BFBA"}}>{t.lines.map(l=>`${int(l.quantity)} × ${l.item}`).join(" + ")}</div><div className="facts"><div><b>{int(t.cases)}</b>boxes</div><div><b>{Math.max(1,Math.ceil(t.cases/48))}</b>pallet{Math.ceil(t.cases/48)===1?"":"s"}</div><div><b style={{fontSize:16,lineHeight:"30px"}}>{sm?.name.split(" · ")[0]||"—"}</b>how it goes</div></div>{o.notes&&<div className="note">Note from sales: {o.notes}</div>}{o.status==="Packed"?<button className="act fin" onClick={()=>ship(o.id)}><Icon name="truck" size={22}/> Mark shipped &amp; notify</button>:<button className="act" onClick={()=>pack(o.id)}><Icon name="check" size={22}/> Mark packed</button>}</div>}):<div style={{color:"#B8BFBA"}}>Nothing to pack right now.</div>}</div></div></div>;
  }

  return <div className="fl">{header}{tabs}
    {job?<>
      <div className="panel" style={{display:"flex",justifyContent:"space-between",gap:16,flexWrap:"wrap"}}><div><div className="k">Now making · {job.id}</div><div className="v">{job.item}{cust?` · ${cust.name}`:` · ${job.purpose}`}</div>{order?.notes&&<div className="k" style={{marginTop:6,color:"#F0C36F"}}>Note from sales: {order.notes}</div>}{job.qcNote&&<div className="k" style={{marginTop:6}}>{job.qcNote}</div>}</div><div style={{textAlign:"right"}}><div className="k">Goal</div><div className="v">{int(job.quantity)}</div></div></div>
      <div className="three"><div className="panel"><div className="k">Good so far</div><div className="v" style={{color:"#6FBF8E"}}>{int(job.good)}</div></div><div className="panel"><div className="k">Scrap</div><div className="v" style={{color:"#F0A48F"}}>{int(job.scrap)}</div></div><div className="panel"><div className="k">Left to make</div><div className="v">{int(Math.max(0,job.quantity-job.good))}</div></div></div>
      <div className="two"><button className="tap good" disabled={job.status==="Paused"} onClick={()=>add(RACK)}>+ {RACK} Good<small>one full rack</small></button><button className="tap scrap" disabled={job.status==="Paused"} onClick={scrap}>+ 1 Scrap<small>tap once per bad bottle</small></button></div>
      <div className="panel" style={{display:"flex",flexDirection:"column",gap:12}}><div className="k">Add a different amount</div><div className="seg"><button className={unit==="racks"?"on":""} onClick={()=>setUnit("racks")}>Racks of {RACK}</button><button className={unit==="bottles"?"on":""} onClick={()=>setUnit("bottles")}>Individual bottles</button></div><input className="bigin" type="number" min={1} value={amount} onChange={e=>setAmount(e.target.value)}/><button className="act fin" disabled={job.status==="Paused"} onClick={()=>add(Math.max(0,parseInt(amount)||0)*(unit==="racks"?RACK:1))}>Add {int(Math.max(0,parseInt(amount)||0)*(unit==="racks"?RACK:1))} bottles</button></div>
      <div className="acts"><button className="act" onClick={pause}><Icon name={job.status==="Paused"?"play":"pause"} size={24}/> {job.status==="Paused"?"Resume":"Pause / problem"}</button><button className="act" disabled={!hist.length} onClick={undo}>Undo last tap{hist.length?` (${hist[hist.length-1].k==="good"?"+"+hist[hist.length-1].n+" good":"+1 scrap"})`:""}</button><button className="act" onClick={qcNote}><Icon name="shield" size={24}/> Quality note</button></div>
      <button className="act fin" style={{height:84,fontSize:24}} onClick={finish}><Icon name="check" size={26}/> Finish run &amp; send to quality</button>
    </>:<div className="panel" style={{textAlign:"center",padding:"40px 24px"}}><div className="v">{line} is idle</div><div className="k">Start the next job below, or ask Chris to release one.</div></div>}
    <div><div className="k" style={{marginBottom:10}}>Up next on {line}</div><div className="queue">{nextUp.length?nextUp.map(w=>{const o=data.orders.find(o=>o.id===w.orderId);const c=o?data.customers.find(c=>c.id===o.customerId):undefined;return <div key={w.id} className="qrow"><span>{w.id} · {w.item} · {c?c.name:w.purpose}{o?.notes&&<em> · {o.notes}</em>}</span><span style={{display:"flex",gap:10,alignItems:"center"}}>{int(w.quantity)} pcs{w.status==="Released"&&!job&&<button className="act" style={{height:40,padding:"0 14px",fontSize:15}} onClick={()=>start(w)}><Icon name="play" size={18}/> Start</button>}{w.status!=="Released"&&<span style={{color:"#6C756F",fontSize:14}}>{w.status}</span>}</span></div>}):<div style={{color:"#B8BFBA"}}>Queue is empty.</div>}</div></div>
    {(data.settings.lines||[]).length>1&&<div style={{display:"flex",gap:8,color:"#B8BFBA",fontSize:15,alignItems:"center"}}>This tablet: {(data.settings.lines||[]).map(l=><button key={l} className={`act ${l===line?"fin":""}`} style={{height:36,padding:"0 12px",fontSize:14}} onClick={()=>go(`warehouse/line/${encodeURIComponent(l)}`)}>{l}</button>)}</div>}
  </div>;
}
