"use client";
import { useState } from "react";
import { DEFAULT_QC, documentTotal, fmtDay, freeStock, int, money, orderTotals, seedData, stageOf, type AppData, type DocumentRecord, type WorkOrder } from "../app-data";
import { Icon, Note, Pill, Stat, nextId, nowLabel, uid, useStore, type Tone } from "./ui";

export const MODS:[string,string,string][]=[["today","Today","clock"],["orders","Orders","list"],["wo","Work orders","box"],["sched","Schedule","cal"],["inv","Inventory","box"],["qc","Quality","shield"],["money","Money","dollar"],["settings","Settings","gear"]];
const stockTone=(free:number,reorder:number):Tone=>free<0?"bad":free<reorder*0.5?"warn":"ok";
const woTone=(s:string):Tone=>s==="Done"?"mute":s==="Running"?"":s==="QC hold"?"warn":s==="Needs scheduling"?"bad":"mute";
const invStatus=(d:DocumentRecord)=>{if(d.status==="Paid"||d.paid>=documentTotal(d))return "Paid";const due=Date.parse(d.due+" "+new Date().getFullYear());if(!isNaN(due)){const days=Math.round((due-Date.now())/864e5);if(days<0)return `Overdue ${-days} days`;if(days<=3)return `Due in ${days} days`}return d.status};

export function ownerCounts(d:AppData){return {orders:d.orders.filter(o=>stageOf(o)<5).length,wo:d.workOrders.filter(w=>w.status!=="Done").length,qc:d.workOrders.filter(w=>w.status==="QC hold").length,inv:d.inventory.filter(i=>i.kind==="raw"?i.onHand<i.reorder&&!i.onOrder:freeStock(i)<i.reorder*0.5).length,money:d.documents.filter(x=>x.kind==="invoice"&&/Overdue|Due/.test(invStatus(x))).length+d.documents.filter(x=>x.status==="Awaiting approval").length} as Record<string,number>}

// =============================================================== TODAY
export function OwnerToday(){
  const {data,commit,toast,go}=useStore();
  const raw=data.inventory.filter(i=>i.kind==="raw");const fin=data.inventory.filter(i=>i.kind!=="raw");
  const running=data.workOrders.find(w=>w.status==="Running");
  const owed=data.documents.filter(x=>x.kind==="invoice"&&invStatus(x)!=="Paid");
  type Item={tone:Tone;h:string;s:string;m:string;act?:React.ReactNode};
  const items:Item[]=[];
  raw.filter(r=>r.onHand<r.reorder).forEach(r=>items.push({tone:r.onOrder?"warn":"bad",h:`${r.item}: ${int(r.onHand)} on hand, reorder at ${int(r.reorder)}`,s:r.onOrder?`${int(r.onOrder)} on order · ETA ${r.eta}. ${r.usage?"Using "+r.usage+".":""}`:`Nothing on order. ${r.usage?"Using "+r.usage+".":""}`,m:"Raw material",act:!r.onOrder&&<button className="sbtn pri" onClick={()=>{commit(v=>({...v,inventory:v.inventory.map(x=>x.id===r.id?{...x,onOrder:x.reorder*2,eta:fmtDay(new Date(Date.now()+21*864e5))}:x)}),"purchase.create",`${r.item} ordered`);toast(`Order placed for ${int(r.reorder*2)} ${r.item}.`)}}>Order {int(r.reorder*2)}</button>}));
  data.workOrders.filter(w=>w.status==="QC hold").forEach(w=>{const o=data.orders.find(o=>o.id===w.orderId);items.push({tone:"warn",h:`${w.id} (${o?data.customers.find(c=>c.id===o.customerId)?.name:"stock"} · ${int(w.quantity)} × ${w.item}) is on quality hold`,s:`${(w.qc||[]).filter(c=>c.result===null).length||6} checks waiting.${o?" Needed "+o.due+".":""}`,m:o?money(orderTotals(o,data).total):"",act:<button className="sbtn pri" onClick={()=>go(`owner/qc/${w.id}`)}>Do the checks</button>})});
  data.orders.filter(o=>stageOf(o)===0).forEach(o=>{const c=data.customers.find(c=>c.id===o.customerId);const wos=data.workOrders.filter(w=>w.orderId===o.id);items.push({tone:"warn",h:`New order ${o.id} · ${c?.name} · ${orderTotals(o,data).lines.map(l=>int(l.quantity)+" × "+l.item).join(" + ")}`,s:`Needed ${o.due}.${wos.length?" "+wos.map(w=>w.id).join(", ")+" created — needs a slot on the schedule.":" From stock — release to the floor."}${(o.discount||0)>(data.settings.discountApproval??5)?` ${o.rep||"Sales"} gave ${o.discount}% off — approve?`:""}`,m:money(orderTotals(o,data).total),act:<><button className="sbtn pri" onClick={()=>go(`owner/so/${o.id}`)}>Open order</button>{wos.length>0&&<button className="sbtn" onClick={()=>go("owner/sched")}>Schedule</button>}</>})});
  data.documents.filter(x=>x.status==="Awaiting approval").forEach(q=>{const c=data.customers.find(c=>c.id===q.customerId);items.push({tone:"warn",h:`Quote ${q.id} for ${c?.name} is priced under the floor`,s:`${q.item} · ${money(q.rate)} each · ${q.discount}% off. Approve or raise to floor.`,m:money(documentTotal(q)),act:<><button className="sbtn pri" onClick={()=>{commit(v=>({...v,documents:v.documents.map(x=>x.id===q.id?{...x,status:"Sent"}:x)}),"quote.approve",`${q.id} approved`);toast(`${q.id} approved and emailed to ${c?.contact}.`)}}>Approve</button><button className="sbtn" onClick={()=>{const fl=data.itemRates.find(r=>q.item.startsWith(r.item))?.floor||q.rate;commit(v=>({...v,documents:v.documents.map(x=>x.id===q.id?{...x,rate:fl,status:"Sent"}:x)}),"quote.raise",`${q.id} raised to floor`);toast(`${q.id} raised to ${money(fl)} and sent.`)}}>Raise to floor</button></>})});
  owed.filter(x=>/Overdue/.test(invStatus(x))).forEach(i=>{const c=data.customers.find(c=>c.id===i.customerId);items.push({tone:"warn",h:`${i.id} ${c?.name} · ${money(documentTotal(i))} · ${invStatus(i).toLowerCase()}`,s:"Send the payment link, or record a payment if it already came in.",m:money(documentTotal(i)),act:<button className="sbtn" onClick={()=>go("owner/money")}>Open Money</button>})});
  fin.filter(i=>freeStock(i)<i.reorder*0.5).forEach(i=>items.push({tone:freeStock(i)<0?"bad":"warn",h:`${i.item}: ${int(freeStock(i))} free (${int(i.onHand)} on shelf, ${int(i.committed)} promised)`,s:data.workOrders.find(w=>w.item===i.item&&w.status!=="Done")?`${data.workOrders.find(w=>w.item===i.item&&w.status!=="Done")!.id} is already covering it.`:"No run scheduled yet.",m:"Finished stock",act:!data.workOrders.find(w=>w.item===i.item&&w.status!=="Done")&&<button className="sbtn" onClick={()=>go("owner/inv")}>Inventory</button>}));
  if(running)items.push({tone:"ok",h:`${running.id} running on ${running.line} · ${int(running.good)} / ${int(running.quantity)} · ${(running.scrap/Math.max(1,running.good+running.scrap)*100).toFixed(1)}% scrap`,s:`${running.purpose}.${running.qcNote?" "+running.qcNote:""}`,m:""});
  return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",flexWrap:"wrap",gap:12}}><h1>What needs you today</h1><span style={{color:"var(--muted)"}}>{new Date().toLocaleDateString("en-US",{weekday:"long",month:"long",day:"numeric"})}</span></div>
    <div className="stats"><Stat k="Orders in progress" v={data.orders.filter(o=>stageOf(o)<5).length} s={`${data.orders.filter(o=>stageOf(o)===0).length} new · ${data.orders.filter(o=>stageOf(o)===3).length} ready`}/><Stat k={running?`${running.line} today`:"Floor"} v={running?`${int(running.good)} / ${int(running.quantity)}`:"Idle"} s={running?`${running.item}`:"no run in progress"}/><Stat k="Money owed to us" v={money(owed.reduce((a,i)=>a+documentTotal(i)-i.paid,0)).replace(".00","")} s={`${owed.filter(x=>/Overdue/.test(invStatus(x))).length} overdue`}/><Stat k="Free finished stock" v={int(fin.reduce((a,i)=>a+Math.max(0,freeStock(i)),0))} s={`${fin.filter(i=>freeStock(i)<i.reorder*0.5).length} below half reorder`}/></div>
    <div className="card">{items.length?items.map((i,k)=><div key={k} className="li" style={{justifyContent:"space-between"}}><div style={{display:"flex",gap:14}}><span className={`dot ${i.tone==="ok"?"":i.tone}`}></span><div><b>{i.h}</b><div className="s">{i.s}</div>{i.act&&<div style={{display:"flex",gap:8,marginTop:10,flexWrap:"wrap"}}>{i.act}</div>}</div></div><b style={{whiteSpace:"nowrap",fontSize:16,color:i.tone==="bad"?"var(--red)":"var(--ink)"}}>{i.m}</b></div>):<div className="empty">Nothing needs you. Enjoy it.</div>}</div></>;
}

// =============================================================== ORDERS
export function OrdersBoard(){
  const {data,go}=useStore();
  const cols:[number,string][]=[[0,"New"],[1,"In production"],[2,"Quality check"],[3,"Ready"],[4,"Shipped / invoicing"]];
  return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",flexWrap:"wrap",gap:12}}><h1>Orders</h1><span style={{color:"var(--muted)"}}>Tap an order to open it. Move it along from inside.</span></div>
    <div className="board" style={{marginTop:22}}>{cols.map(([st,n])=>{const list=data.orders.filter(o=>st===4?stageOf(o)>=4&&stageOf(o)<6:stageOf(o)===st);return <div key={n} className="col"><h4>{n}<span>{list.length}</span></h4>{list.map(o=>{const c=data.customers.find(c=>c.id===o.customerId);return <button key={o.id} className="ocard" onClick={()=>go(`owner/so/${o.id}`)}><b>{c?.name}</b>{orderTotals(o,data).lines.map(l=>int(l.quantity)+" × "+l.item.split(" · ")[0]).join(" + ")}<div className="m">{o.id} · {o.due}{o.invoiceId?" · "+o.invoiceId:""}</div>{o.notes&&<div className="m" style={{color:"var(--amber)"}}>Note: {o.notes}</div>}</button>})}{!list.length&&<div style={{color:"var(--muted)",fontSize:14,padding:6}}>Nothing here</div>}</div>})}</div>
    <h2 style={{marginTop:28}}>Paid and closed</h2><div className="card wrapx" style={{marginTop:10,padding:"0 10px"}}><table className="tbl"><tbody>{data.orders.filter(o=>stageOf(o)===6).map(o=><tr key={o.id} className="click" onClick={()=>go(`owner/so/${o.id}`)}><td><b>{o.id}</b></td><td>{data.customers.find(c=>c.id===o.customerId)?.name}</td><td>{o.due}</td><td>{o.invoiceId} <Pill>Paid</Pill></td><td className="n">{money(orderTotals(o,data).total)}</td></tr>)}</tbody></table></div></>;
}

// =============================================================== WORK ORDERS
export function WorkOrders({selected}:{selected?:string}){
  const {data,commit,toast,go}=useStore();
  const w=data.workOrders.find(x=>x.id===selected)||data.workOrders.find(x=>x.status==="Running")||data.workOrders[0];
  const rate=w?data.itemRates.find(r=>r.item===w.item):undefined;const so=w?data.orders.find(o=>o.id===w.orderId):undefined;const cust=so?data.customers.find(c=>c.id===so.customerId):undefined;
  const upd=(id:string,patch:Partial<WorkOrder>,action:string,summary:string)=>commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===id?{...x,...patch}:x)}),action,summary);
  const create=()=>{const item=data.itemRates.find(r=>r.kind!=="raw")?.item||"";const id=nextId("WO-",data.workOrders.map(x=>x.id),116);commit(v=>({...v,workOrders:[...v.workOrders,{id,item,quantity:500,good:0,scrap:0,packed:0,date:new Date().toISOString().slice(0,10),status:"Needs scheduling",purpose:"Build stock",line:"Line 1",days:1}]}),"wo.create",`${id} created`);go(`owner/wo/${id}`);toast(`${id} created for stock — give it a slot on the schedule.`)};
  const dayName=(w:WorkOrder)=>{const d=new Date(w.date+"T12:00:00");return d.toLocaleDateString("en-US",{weekday:"short"})};
  return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",flexWrap:"wrap",gap:12}}><h1>Work orders</h1><button className="sbtn pri" onClick={create}><Icon name="plus" size={18}/> New work order</button></div>
    <div className="split" style={{marginTop:20}}><div className="card wrapx" style={{padding:"0 10px"}}><table className="tbl"><thead><tr><th>WO</th><th>Making</th><th>For</th><th>Line · when</th><th>Progress</th><th>Status</th></tr></thead><tbody>{data.workOrders.map(x=>{const pct=Math.min(100,Math.round(x.good/Math.max(1,x.quantity)*100));const o=data.orders.find(o=>o.id===x.orderId);return <tr key={x.id} className="click" style={w&&x.id===w.id?{background:"#faf9f5"}:undefined} onClick={()=>go(`owner/wo/${x.id}`)}><td><b>{x.id}</b></td><td>{int(x.quantity)} × {x.item}</td><td>{o?`${o.id} · ${data.customers.find(c=>c.id===o.customerId)?.name.split(" ")[0]||""}`:"Stock"}</td><td style={{color:"var(--muted)"}}>{x.line} · {dayName(x)}{(x.days||1)>1?` +${(x.days||1)-1}d`:""}</td><td><div className={`bar ${x.status==="QC hold"?"warn":""}`}><i style={{width:pct+"%"}}></i></div><small style={{color:"var(--muted)"}}>{int(x.good)} / {int(x.quantity)}</small></td><td><Pill tone={woTone(x.status)}>{x.status}</Pill></td></tr>})}</tbody></table></div>
    {w&&<div className="card pad" style={{display:"flex",flexDirection:"column",gap:16}}><div><div style={{fontSize:14,color:"var(--muted)",fontWeight:600,textTransform:"uppercase",letterSpacing:".06em"}}>{w.id}</div><div style={{fontSize:26,fontWeight:700}}>{int(w.quantity)} × {w.item}</div><div style={{color:"var(--muted)"}}>{so?`For ${so.id} · ${cust?.name} · needed ${so.due}`:w.purpose}</div></div>
      <div className="sum" style={{border:0,padding:0}}><div><span style={{color:"var(--muted)"}}>Material</span><b>{rate?.material||"—"} × {int(w.quantity+Math.round(w.quantity*0.03))}</b></div><div><span style={{color:"var(--muted)"}}>Line</span><span style={{display:"flex",gap:6}}>{(data.settings.lines||["Line 1","Line 2"]).map(l=><button key={l} className={`sbtn ${w.line===l?"pri":""}`} style={{height:34,fontSize:14}} onClick={()=>upd(w.id,{line:l},"wo.line",`${w.id} → ${l}`)}>{l}</button>)}</span></div><div><span style={{color:"var(--muted)"}}>Quantity</span><input className="inp" style={{width:110,height:38,textAlign:"right"}} type="number" value={w.quantity} onChange={e=>upd(w.id,{quantity:Math.max(1,parseInt(e.target.value)||1)},"wo.qty",`${w.id} qty`)}/></div><div><span style={{color:"var(--muted)"}}>Made / scrap</span><b>{int(w.good)} / {w.scrap} ({w.good?(w.scrap/(w.good+w.scrap)*100).toFixed(1):"0.0"}%)</b></div><div><span style={{color:"var(--muted)"}}>Quality</span><b>{w.qcResult==="pass"?"Passed":w.status==="QC hold"?`${(w.qc||[]).filter(c=>c.result===null).length||(rate?.qcChecks||DEFAULT_QC).length} checks waiting`:w.qc?`${w.qc.filter(c=>c.result!==null).length} of ${w.qc.length} done`:"Not started"}</b></div>{so?.notes&&<div><span style={{color:"var(--muted)"}}>Note from sales</span><b style={{textAlign:"right"}}>{so.notes}</b></div>}</div>
      <div style={{display:"flex",gap:8,flexWrap:"wrap"}}>
        {w.status==="Needs scheduling"&&<><button className="sbtn pri" onClick={()=>{const d=new Date();d.setDate(d.getDate()+((8-d.getDay())%7||7));upd(w.id,{status:"Scheduled",date:d.toISOString().slice(0,10)},"wo.schedule",`${w.id} scheduled`);toast(`${w.id} scheduled for Monday on ${w.line}.`)}}>Put on Monday · {w.line}</button><button className="sbtn" onClick={()=>go("owner/sched")}>Open schedule</button></>}
        {w.status==="Scheduled"&&<button className="sbtn pri" onClick={()=>{upd(w.id,{status:"Released"},"wo.release",`${w.id} released`);toast(`${w.id} released — it shows on the ${w.line} tablet queue.`)}}>Release to floor</button>}
        {(w.status==="Released")&&<button className="sbtn pri" onClick={()=>{commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,status:"Running"}:x.status==="Running"&&x.line===w.line?{...x,status:"Paused"}:x),orders:v.orders.map(o=>o.id===w.orderId&&stageOf(o)<1?{...o,stage:1,status:"In production"}:o)}),"wo.start",`${w.id} started`);toast(`${w.id} is now running on ${w.line}.`)}}>Start run</button>}
        {(w.status==="QC hold"||w.status==="Running")&&<button className="sbtn pri" onClick={()=>go(`owner/qc/${w.id}`)}>Quality checks</button>}
        {w.status==="Done"&&<Pill>Done · into stock</Pill>}
        <button className="sbtn" onClick={()=>toast(`Traveler printed for ${w.id}.`)}>Print traveler</button>
      </div></div>}</div></>;
}

// =============================================================== SCHEDULE
export function Schedule(){
  const {data,commit,toast,go}=useStore();
  const lines=data.settings.lines||["Line 1","Line 2"];
  const start=new Date();start.setHours(12,0,0,0);
  const days=Array.from({length:7},(_,i)=>{const d=new Date(start);d.setDate(d.getDate()+i);return d}).filter(d=>d.getDay()!==0&&d.getDay()!==6).slice(0,5);
  const key=(d:Date)=>d.toISOString().slice(0,10);
  const covers=(w:WorkOrder,d:Date)=>{const s=new Date(w.date+"T12:00:00");const diff=Math.round((d.getTime()-s.getTime())/864e5);return diff>=0&&diff<(w.days||1)};
  const shift=(w:WorkOrder,delta:number)=>{if(w.status==="Done"||w.status==="Running"){toast(`${w.id} is ${w.status.toLowerCase()} — it can't move.`);return}const d=new Date(w.date+"T12:00:00");d.setDate(d.getDate()+delta);commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,date:key(d),status:x.status==="Needs scheduling"?"Scheduled":x.status}:x)}),"wo.move",`${w.id} moved`);toast(`${w.id} moved to ${fmtDay(d)}.`)};
  const waiting=data.workOrders.filter(w=>w.status==="Needs scheduling");
  const lowRaw=data.inventory.filter(i=>i.kind==="raw"&&i.onHand<i.reorder);
  return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",flexWrap:"wrap",gap:12}}><h1>This week on the floor</h1><span style={{color:"var(--muted)"}}>Tap a job to push it a day later. Unscheduled work orders sit below.</span></div>
    <div className="wrapx" style={{marginTop:20}}><div className="sched" style={{gridTemplateColumns:`120px repeat(${days.length},minmax(0,1fr))`}}><div></div>{days.map(d=><div key={key(d)} className="hd">{d.toLocaleDateString("en-US",{weekday:"short"})} {d.getDate()}</div>)}
      {lines.map(ln=><span key={ln} style={{display:"contents"}}><div className="ln">{ln}</div>{days.map((d,di)=>{const here=data.workOrders.filter(w=>w.line===ln&&w.status!=="Needs scheduling"&&covers(w,d));return <div key={key(d)} className="cell">{here.map(w=>{const o=data.orders.find(o=>o.id===w.orderId);const c=o?data.customers.find(c=>c.id===o.customerId):undefined;const t=w.status==="Done"?"mute":w.status==="QC hold"?"warn":w.status==="Running"?"":"mute";return <button key={w.id} className={`blk ${t}`} style={{textAlign:"left",cursor:"pointer"}} onClick={()=>shift(w,1)} onDoubleClick={()=>go(`owner/wo/${w.id}`)}>{w.id} · {int(w.quantity)} × {w.item.split(" · ")[0]}<small>{c?c.name:w.purpose} · {w.status}</small></button>})}{di===days.length-1&&lowRaw.map(r=><div key={r.id} className="blk bad" style={{cursor:"default"}}>{r.item.split(" · ")[0]} low<small>{r.onOrder?`${int(r.onOrder)} land ${r.eta}`:"nothing on order"}</small></div>)}</div>})}</span>)}
    </div></div>
    <h2 style={{marginTop:26}}>Waiting for a slot</h2><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:10}}>{waiting.length?waiting.map(w=>{const o=data.orders.find(o=>o.id===w.orderId);const c=o?data.customers.find(c=>c.id===o.customerId):undefined;return <div key={w.id} className="ocard" style={{display:"flex",gap:12,alignItems:"center",cursor:"default",flexWrap:"wrap"}}><div><b>{w.id} · {int(w.quantity)} × {w.item}</b><span className="m">{c?`${c.name} · needed ${o?.due}`:w.purpose}</span></div>{lines.map(ln=><button key={ln} className={ln===lines[0]?"sbtn pri":"sbtn"} onClick={()=>{const d=new Date();d.setDate(d.getDate()+((8-d.getDay())%7||7));commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,status:"Scheduled",line:ln,date:key(d)}:x)}),"wo.schedule",`${w.id} → ${ln}`);toast(`${w.id} → Monday, ${ln}.`)}}>Mon · {ln}</button>)}</div>}):<span style={{color:"var(--muted)"}}>Everything has a slot.</span>}</div></>;
}

// =============================================================== INVENTORY
export function Inventory(){
  const {data,commit,toast}=useStore();
  const fin=data.inventory.filter(i=>i.kind!=="raw");const raw=data.inventory.filter(i=>i.kind==="raw");
  const makeRun=(item:string)=>{const id=nextId("WO-",data.workOrders.map(x=>x.id),116);commit(v=>({...v,workOrders:[...v.workOrders,{id,item,quantity:500,good:0,scrap:0,packed:0,date:new Date().toISOString().slice(0,10),status:"Needs scheduling",purpose:"Build stock",line:"Line 1",days:1}]}),"wo.create",`${id} for stock`);toast(`${id} created — 500 × ${item} for stock. Give it a slot on the schedule.`)};
  return <><h1>Inventory</h1><div className="sub">Finished goods first, then what we make them from. “Free” = on shelf minus promised.</div>
    <h2 style={{marginTop:22}}>Finished goods</h2><div className="card wrapx" style={{marginTop:10,padding:"0 10px"}}><table className="tbl"><thead><tr><th>Product</th><th className="n">On shelf</th><th className="n">Promised</th><th className="n">Free</th><th className="n">Reorder at</th><th>Cost · margin</th><th></th></tr></thead><tbody>{fin.map(i=>{const free=freeStock(i);const tone=stockTone(free,i.reorder);const r=data.itemRates.find(r=>r.item===i.item);const covered=data.workOrders.find(w=>w.item===i.item&&w.status!=="Done");return <tr key={i.id}><td style={{fontWeight:600}}>{i.item}</td><td className="n"><input className="inp" style={{width:90,height:36,textAlign:"right",padding:"0 8px"}} type="number" value={i.onHand} onChange={e=>commit(v=>({...v,inventory:v.inventory.map(x=>x.id===i.id?{...x,onHand:Math.max(0,parseInt(e.target.value)||0)}:x)}),"inventory.count",`${i.item} counted`)}/></td><td className="n" style={{color:"var(--muted)"}}>{int(i.committed)}</td><td className="n" style={{fontWeight:700,color:`var(--${tone==="ok"?"green":tone==="warn"?"amber":"red"})`}}>{int(free)}</td><td className="n" style={{color:"var(--muted)"}}>{int(i.reorder)}</td><td>{money(i.cost)}{r?<> · <b>{Math.round((r.rate-i.cost)/r.rate*100)}%</b> at list</>:null}</td><td style={{textAlign:"right"}}>{tone!=="ok"&&(covered?<Pill tone="warn">{covered.id} · {covered.status}</Pill>:<button className="sbtn" onClick={()=>makeRun(i.item)}>Make 500</button>)}</td></tr>})}</tbody></table></div>
    <h2 style={{marginTop:26}}>Raw materials &amp; packaging</h2><div className="card wrapx" style={{marginTop:10,padding:"0 10px"}}><table className="tbl"><thead><tr><th>Material</th><th className="n">On hand</th><th className="n">Reorder at</th><th>Usage</th><th>On order</th><th></th></tr></thead><tbody>{raw.map(r=>{const low=r.onHand<r.reorder;return <tr key={r.id}><td style={{fontWeight:600}}>{r.item}</td><td className="n"><input className="inp" style={{width:100,height:36,textAlign:"right",padding:"0 8px",fontWeight:700,color:low?(r.onOrder?"var(--amber)":"var(--red)"):"var(--ink)"}} type="number" value={r.onHand} onChange={e=>commit(v=>({...v,inventory:v.inventory.map(x=>x.id===r.id?{...x,onHand:Math.max(0,parseInt(e.target.value)||0)}:x)}),"inventory.count",`${r.item} counted`)}/></td><td className="n" style={{color:"var(--muted)"}}>{int(r.reorder)}</td><td style={{color:"var(--muted)"}}>{r.usage||"—"}</td><td>{r.onOrder?<>{int(r.onOrder)} · ETA {r.eta} <button className="sbtn" style={{height:32,fontSize:13}} onClick={()=>{commit(v=>({...v,inventory:v.inventory.map(x=>x.id===r.id?{...x,onHand:x.onHand+(x.onOrder||0),onOrder:0,eta:undefined}:x)}),"inventory.receive",`${r.item} received`);toast(`Received ${int(r.onOrder||0)} ${r.item}. Enter the container's freight and duty in Money to update landed cost.`)}}>Received</button></>:"—"}</td><td style={{textAlign:"right"}}>{low&&!r.onOrder&&<button className="sbtn pri" onClick={()=>{commit(v=>({...v,inventory:v.inventory.map(x=>x.id===r.id?{...x,onOrder:x.reorder*2,eta:fmtDay(new Date(Date.now()+21*864e5))}:x)}),"purchase.create",`${r.item} ordered`);toast(`Order placed for ${int(r.reorder*2)} ${r.item}.`)}}>Order {int(r.reorder*2)}</button>}</td></tr>})}</tbody></table></div>
    <div style={{color:"var(--muted)",fontSize:16,marginTop:14}}>Every finished run subtracts its material automatically (see the work order&apos;s Material line); counts here are the shelf truth — correct them whenever you count.</div></>;
}

// =============================================================== QUALITY
export function Quality({selected}:{selected?:string}){
  const {data,commit,toast,go}=useStore();
  const cands=data.workOrders.filter(w=>w.status==="QC hold"||w.status==="Running"||(w.qc&&w.qcResult!=="pass"));
  const w=data.workOrders.find(x=>x.id===selected)||cands[0];
  if(!w)return <><h1>Quality checks</h1><div className="empty">No runs waiting for checks.</div></>;
  const rate=data.itemRates.find(r=>r.item===w.item);const checks=w.qc||(rate?.qcChecks||DEFAULT_QC).map(l=>({label:l,result:null as boolean|null}));
  const done=checks.filter(c=>c.result!==null).length;const fails=checks.filter(c=>c.result===false).length;
  const setCheck=(i:number,r:boolean)=>commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,qc:checks.map((c,k)=>k===i?{...c,result:r}:c)}:x)}),"qc.check",`${w.id} check`);
  const pass=()=>{commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,qcResult:"pass",status:"Done"}:x),inventory:v.inventory.map(row=>row.item===w.item?{...row,onHand:row.onHand+w.good}:row),orders:v.orders.map(o=>o.id===w.orderId&&stageOf(o)<3?{...o,stage:3,status:"Ready"}:o),notices:[{id:uid("n"),title:`${w.id} passed quality`,detail:`${int(w.good)} × ${w.item} into stock${w.orderId?` · ${w.orderId} is Ready`:""}`,urgent:false,read:false,createdAt:nowLabel(),target:"Orders"},...v.notices]}),"qc.pass",`${w.id} passed`);toast(`${w.id} passed — ${int(w.good)} into stock${w.orderId?"; "+w.orderId+" moved to Ready":""}.`)};
  const hold=()=>{commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,qcResult:"hold",status:"QC hold"}:x)}),"qc.hold",`${w.id} held`);toast(`Batch held. ${w.orderId?w.orderId+" shows quality hold; ":""}the floor gets the note.`)};
  const scrap=()=>{commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,qcResult:"scrap",scrap:x.scrap+x.good,good:0,status:"Scheduled",qc:undefined}:x)}),"qc.scrap",`${w.id} scrapped`);toast(`${w.id} scrapped to regrind and re-queued.`)};
  return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",flexWrap:"wrap",gap:12}}><h1>Quality checks</h1><div style={{display:"flex",gap:8,flexWrap:"wrap"}}>{cands.map(x=><button key={x.id} className={`sbtn ${x.id===w.id?"pri":""}`} onClick={()=>go(`owner/qc/${x.id}`)}>{x.id} · {x.item.split(" · ")[0]}</button>)}</div></div>
    <div className="split" style={{marginTop:20}}><div><div className="sub" style={{margin:"0 0 14px"}}>{w.id} · {int(w.quantity)} × {w.item} · {w.line} · {done} of {checks.length} checks done</div>
      <div className="qc">{checks.map((c,i)=><div key={c.label} className="chk"><span style={{fontWeight:600}}>{c.label}</span><span className="pf"><button className={`p ${c.result===true?"on":""}`} aria-label="pass" onClick={()=>setCheck(i,true)}>✓</button><button className={`f ${c.result===false?"on":""}`} aria-label="fail" onClick={()=>setCheck(i,false)}>✗</button></span></div>)}</div>
      <div className="field" style={{marginTop:16}}><label htmlFor="qc-note">Notes for this run</label><textarea id="qc-note" className="inp" value={w.qcNote||""} onChange={e=>commit(v=>({...v,workOrders:v.workOrders.map(x=>x.id===w.id?{...x,qcNote:e.target.value}:x)}),"qc.note",`${w.id} note`)}/></div></div>
    <div className="card pad" style={{display:"flex",flexDirection:"column",gap:14}}><h2>Decision</h2>
      {fails?<Note tone="bad" icon="clock" big={`${fails} check${fails>1?"s":""} failed.`}>Hold the batch, scrap it, or fix and re-check. {w.orderId?`${w.orderId} shows “quality hold” either way.`:""}</Note>:done<checks.length?<Note tone="warn" icon="clock" big={`${checks.length-done} to go.`}>The run can&apos;t go into stock until every check is in.</Note>:<Note icon="check" big="All passed.">Release it: {int(w.good)} go into stock{w.orderId?` and ${w.orderId} moves to Ready`:""}.</Note>}
      <div style={{display:"flex",flexDirection:"column",gap:8}}><button className="btn" disabled={done<checks.length||fails>0||w.status==="Done"} onClick={pass}><Icon name="check"/> Pass &amp; release to stock</button><button className="btn sec" disabled={!fails} onClick={hold}>Hold the batch</button><button className="btn sec" style={{borderColor:"var(--red)",color:"var(--red)"}} disabled={!fails} onClick={scrap}>Scrap to regrind &amp; re-run</button></div>
      <div style={{color:"var(--muted)",fontSize:15}}>Every check is saved against the run, so a complaint months later traces back to the batch, the line, the material lot and who checked it.</div></div></div></>;
}

// =============================================================== MONEY
export function Money(){
  const {data,commit,toast,go}=useStore();
  const invs=data.documents.filter(x=>x.kind==="invoice");const quotes=data.documents.filter(x=>x.kind==="quote");
  const open=invs.filter(i=>invStatus(i)!=="Paid");const overdue=open.filter(i=>/Overdue/.test(invStatus(i)));
  const ready=data.orders.filter(o=>stageOf(o)===4&&!o.invoiceId);
  const pay=(i:DocumentRecord)=>commit(v=>({...v,documents:v.documents.map(x=>x.id===i.id?{...x,status:"Paid",paid:documentTotal(x)}:x),orders:v.orders.map(o=>o.invoiceId===i.id?{...o,stage:6,status:"Paid",payment:"Paid"}:o),customers:v.customers.map(c=>c.id===i.customerId?{...c,balance:Math.max(0,c.balance-documentTotal(i))}:c)}),"payment.record",`${i.id} paid`);
  const qb=data.settings.quickBooks;
  return <><div style={{display:"flex",justifyContent:"space-between",alignItems:"baseline",flexWrap:"wrap",gap:12}}><h1>Money</h1>{qb.connected?<span className="qb"><i></i>QuickBooks Online · synced {qb.lastSync}</span>:<button className="sbtn pri" onClick={()=>go("owner/settings")}>Connect QuickBooks</button>}</div>
    <div className="stats"><Stat k="Owed to us" v={money(open.reduce((a,i)=>a+documentTotal(i)-i.paid,0)).replace(".00","")} s={`${open.length} open invoices`}/><Stat k="Overdue" v={<span style={{color:overdue.length?"var(--red)":"inherit"}}>{money(overdue.reduce((a,i)=>a+documentTotal(i)-i.paid,0)).replace(".00","")}</span>} s={`${overdue.length} invoice${overdue.length===1?"":"s"}`}/><Stat k="Paid this month" v={money(invs.filter(i=>invStatus(i)==="Paid").reduce((a,i)=>a+documentTotal(i),0)).replace(".00","")} s={`${invs.filter(i=>invStatus(i)==="Paid").length} invoices`}/><Stat k="Ready to invoice" v={ready.length} s="shipped, no invoice yet"/></div>
    <div className="card wrapx" style={{padding:"0 10px"}}><table className="tbl"><thead><tr><th>Invoice</th><th>Customer</th><th>Order</th><th>Due</th><th>Status</th><th className="n">Amount</th><th></th></tr></thead><tbody>{invs.map(i=>{const st=invStatus(i);const c=data.customers.find(c=>c.id===i.customerId);return <tr key={i.id}><td><b>{i.id}</b></td><td>{c?.name}</td><td style={{color:"var(--muted)"}}>{i.orderId?<button className="btn link" style={{fontSize:16}} onClick={()=>go(`owner/so/${i.orderId}`)}>{i.orderId}</button>:"—"}</td><td>{i.due}</td><td><Pill tone={st==="Paid"?"":/Overdue/.test(st)?"bad":/Due/.test(st)?"warn":"mute"}>{st}</Pill></td><td className="n" style={{fontWeight:600}}>{money(documentTotal(i))}</td><td style={{textAlign:"right",whiteSpace:"nowrap"}}>{st!=="Paid"&&<><button className="sbtn" onClick={()=>toast(`Payment link sent to ${c?.contact}.`)}>Send link</button> <button className="sbtn pri" onClick={()=>{pay(i);toast(`${i.id} marked paid — synced to QuickBooks.`)}}>Record payment</button></>}</td></tr>})}</tbody></table></div>
    <h2 style={{marginTop:26}}>Shipped, not yet invoiced</h2><div style={{display:"flex",gap:10,flexWrap:"wrap",marginTop:10}}>{ready.length?ready.map(o=>{const c=data.customers.find(c=>c.id===o.customerId);return <div key={o.id} className="ocard" style={{display:"flex",gap:14,alignItems:"center",cursor:"default"}}><div><b>{o.id} · {c?.name}</b><span className="m">{money(orderTotals(o,data).total)} · {c?.terms}</span></div><button className="sbtn pri" onClick={()=>go(`owner/so/${o.id}`)}><Icon name="doc" size={16}/> Create invoice</button></div>}):<span style={{color:"var(--muted)"}}>All shipped orders are invoiced.</span>}</div>
    <h2 style={{marginTop:26}}>Quotes</h2><div className="card wrapx" style={{marginTop:10,padding:"0 10px"}}><table className="tbl"><tbody>{quotes.length?quotes.map(q=>{const c=data.customers.find(c=>c.id===q.customerId);return <tr key={q.id}><td><b>{q.id}</b></td><td>{c?.name}</td><td>{q.item}</td><td><Pill tone={q.status==="Awaiting approval"?"warn":q.status==="Accepted"?"":"mute"}>{q.status}</Pill></td><td className="n">{money(documentTotal(q))}</td><td style={{textAlign:"right",whiteSpace:"nowrap"}}>{q.status==="Awaiting approval"&&<button className="sbtn pri" onClick={()=>{commit(v=>({...v,documents:v.documents.map(x=>x.id===q.id?{...x,status:"Sent"}:x)}),"quote.approve",`${q.id} approved`);toast(`${q.id} approved and sent.`)}}>Approve</button>}{q.status==="Sent"&&<button className="sbtn" onClick={()=>{commit(v=>({...v,documents:v.documents.map(x=>x.id===q.id?{...x,status:"Accepted"}:x)}),"quote.accept",`${q.id} accepted`);toast(`${q.id} marked accepted — start the order from the customer's page.`)}}>Customer said yes</button>}</td></tr>}):<tr><td className="empty">No quotes yet.</td></tr>}</tbody></table></div>
    <div style={{color:"var(--muted)",fontSize:16,marginTop:16}}>Invoices, payments, customers and items are created in QuickBooks Online through its API — this app never keeps a second set of books. Card and ACH payments come through QuickBooks Payments links; sales can send one from any order.</div></>;
}

// =============================================================== SETTINGS
export function Settings(){
  const {data,commit,toast}=useStore();const s=data.settings;
  const upd=(patch:Partial<AppData["settings"]>,summary:string)=>commit(v=>({...v,settings:{...v.settings,...patch}}),"settings",summary);
  const [confirmReset,setConfirmReset]=useState(false);
  const url=typeof window!=="undefined"?`${window.location.origin}${window.location.pathname}#warehouse`:"/#warehouse";
  return <><h1>Settings</h1><div className="sub">Prices, floors, shipping, QuickBooks and who can see what.</div>
    <div className="settings-grid">
      <div className="card pad" style={{display:"flex",flexDirection:"column",gap:12}}><h2>Prices &amp; floors</h2><div style={{color:"var(--muted)",fontSize:15}}>List price is what a new customer pays. Below the floor, sales needs your approval.</div><div className="kv-list">{data.itemRates.filter(r=>r.kind!=="raw").map(r=><div key={r.id}><span>{r.item}</span><span style={{display:"flex",gap:6,alignItems:"center"}}><input type="number" step="0.05" value={r.rate} onChange={e=>commit(v=>({...v,itemRates:v.itemRates.map(x=>x.id===r.id?{...x,rate:parseFloat(e.target.value)||0}:x)}),"rate",`${r.item} price`)}/><span style={{color:"var(--muted)"}}>floor</span><input type="number" step="0.05" value={r.floor} onChange={e=>commit(v=>({...v,itemRates:v.itemRates.map(x=>x.id===r.id?{...x,floor:parseFloat(e.target.value)||0}:x)}),"rate",`${r.item} floor`)}/></span></div>)}</div><div className="kv-list"><div><span>Discount needing my approval</span><span><input type="number" value={s.discountApproval??5} onChange={e=>upd({discountApproval:parseFloat(e.target.value)||0},"discount limit")}/> %</span></div></div></div>
      <div className="card pad" style={{display:"flex",flexDirection:"column",gap:12}}><h2>Shipping options</h2><div className="kv-list">{(s.shipMethods||[]).map(m=><div key={m.id}><span>{m.name}<br/><small style={{color:"var(--muted)"}}>{m.sub}</small></span><span>{m.perCase!=null?<><input type="number" step="0.1" value={m.perCase} onChange={e=>upd({shipMethods:(s.shipMethods||[]).map(x=>x.id===m.id?{...x,perCase:parseFloat(e.target.value)||0}:x)},"ship rate")}/> /box</>:<input type="number" value={m.rate} onChange={e=>upd({shipMethods:(s.shipMethods||[]).map(x=>x.id===m.id?{...x,rate:parseFloat(e.target.value)||0}:x)},"ship rate")}/>}</span></div>)}</div><div className="kv-list"><div><span>Production lines</span><span>{(s.lines||[]).join(", ")}</span></div></div></div>
      <div className="card pad" style={{display:"flex",flexDirection:"column",gap:12}}><h2>QuickBooks Online</h2>{s.quickBooks.connected?<><span className="qb" style={{alignSelf:"flex-start"}}><i></i>Connected · company {s.quickBooks.realmId}</span><div style={{color:"var(--muted)",fontSize:15}}>Customers, invoices and payments sync both ways. Last sync {s.quickBooks.lastSync}.</div><button className="sbtn" onClick={()=>{upd({quickBooks:{...s.quickBooks,lastSync:"just now"}},"qb sync");toast("QuickBooks sync finished — nothing to reconcile.")}}>Sync now</button></>:<><div style={{color:"var(--muted)",fontSize:15}}>Connect once and every invoice, payment and customer is created in QuickBooks instead of here.</div><button className="btn" onClick={()=>{upd({quickBooks:{...s.quickBooks,connected:true,realmId:"pending",lastSync:"just now"}},"qb connect");toast("QuickBooks connected. (Live OAuth is wired at deploy time.)")}}>Connect QuickBooks</button></>}</div>
      <div className="card pad" style={{display:"flex",flexDirection:"column",gap:12}}><h2>People &amp; access</h2><div className="kv-list">{data.roles.map(r=><div key={r.id}><span><b>{r.name}</b><br/><small style={{color:"var(--muted)"}}>{r.members.join(", ")}</small></span><span style={{color:"var(--muted)",fontSize:14,textAlign:"right"}}>{r.permissions.all==="edit"?"Everything":Object.entries(r.permissions).filter(([,v])=>v!=="none").map(([k,v])=>`${k}: ${v}`).join(" · ")}</span></div>)}</div><div style={{color:"var(--muted)",fontSize:15}}>Floor tablet link: <code style={{fontSize:14}}>{url}</code></div></div>
      <div className="card pad" style={{display:"flex",flexDirection:"column",gap:12}}><h2>Company</h2><div className="kv-list"><div><span>Company</span><input style={{width:200,textAlign:"left"}} value={s.company} onChange={e=>upd({company:e.target.value},"company name")}/></div><div><span>Owner</span><span>{s.ownerName}</span></div></div><div style={{borderTop:"2px solid var(--line)",paddingTop:12,display:"flex",flexDirection:"column",gap:8}}><div style={{color:"var(--muted)",fontSize:15}}>Still seeing the old Pure Alkaline test records? Load the EcoForm starter data. This replaces everything saved so far.</div>{confirmReset?<div style={{display:"flex",gap:8}}><button className="sbtn danger" onClick={()=>{commit(()=>seedData,"reset","Loaded EcoForm starter data");setConfirmReset(false);toast("EcoForm starter data loaded.")}}>Yes, replace everything</button><button className="sbtn" onClick={()=>setConfirmReset(false)}>Cancel</button></div>:<button className="sbtn" onClick={()=>setConfirmReset(true)}>Load EcoForm starter data…</button>}</div></div>
    </div></>;
}
