"use client";
import { useState } from "react";
import { documentTotal, freeStock, orderTotals, seedData, stageOf, isLegacySeed, type InventoryRow } from "../app-data";
import { CheckRow, ControlMetric, Decision, Kpi, MiniRow, PlRow, ReportCard, SettingRow, StatusLine, SyncToggle, downloadCsv, num, useApp, usd, usd2 } from "./store";
import { Customers, DocList, Leads, OrdersPage, ProductionCalendar } from "./sales";

export const ownerGroups=[
  {label:"Sales & customers",items:["Customers","Leads","Orders","Invoices","Quotes"]},
  {label:"Production",items:["Work orders","Production calendar","Quality","Maintenance"]},
  {label:"Inventory & purchasing",items:["Inventory","Purchasing","Item rates"]},
  {label:"Financials",items:["Profit & loss","Reports"]},
  {label:"Administration",items:["Settings & access"]},
];

export function OwnerView({nav}:{nav:string}){
  if(nav==="Customers")return <Customers/>;
  if(nav==="Leads")return <Leads/>;
  if(nav==="Orders")return <OrdersPage/>;
  if(nav==="Invoices")return <DocList kind="invoice"/>;
  if(nav==="Quotes")return <DocList kind="quote"/>;
  if(nav==="Work orders")return <WorkOrders/>;
  if(nav==="Production calendar")return <ProductionCalendar audience="owner"/>;
  if(nav==="Item rates")return <ItemRates/>;
  if(nav==="Inventory")return <InventoryWorkspace/>;
  if(nav==="Quality")return <QualityWorkspace/>;
  if(nav==="Maintenance")return <MaintenanceWorkspace/>;
  if(nav==="Purchasing")return <PurchasingWorkspace/>;
  if(nav==="Profit & loss")return <ProfitLoss/>;
  if(nav==="Reports")return <ReportsWorkspace/>;
  if(nav==="Settings & access")return <SettingsWorkspace/>;
  return <OwnerControlCenter/>;
}

// helpers shared by owner screens
const invStatus=(d:{status:string;paid:number;due:string},total:number)=>{if(d.status==="Paid"||d.paid>=total)return "Paid";const t=Date.parse(`${d.due} ${new Date().getFullYear()}`);if(!isNaN(t)){const days=Math.round((t-Date.now())/864e5);if(days<0)return `Overdue ${-days}d`;if(days<=3)return `Due in ${days}d`}return d.status};
const stockState=(r:InventoryRow)=>{const free=r.kind==="raw"?r.onHand:freeStock(r);return free<0?"Short":free<r.reorder*0.5?"Order now":free<r.reorder?"Order soon":"Good"};

// =============================================================== CONTROL CENTER (live)
export function OwnerControlCenter(){
  const {data,setNav,setModal,openRecord,openCustomer,commit,notify}=useApp();const [search,setSearch]=useState("");
  const q=search.trim().toLowerCase();
  const matches=q?[...data.customers.filter(c=>c.name.toLowerCase().includes(q)).map(c=>({label:`${c.name} · ${c.kind}`,go:()=>openCustomer(c.id)})),...data.orders.filter(o=>o.id.toLowerCase().includes(q)).map(o=>({label:`${o.id} · Order · ${o.status}`,go:()=>openRecord(o.id)})),...data.workOrders.filter(w=>w.id.toLowerCase().includes(q)||w.item.toLowerCase().includes(q)).map(w=>({label:`${w.id} · ${w.item} · ${w.status}`,go:()=>openRecord(w.id)})),...data.documents.filter(d=>d.id.toLowerCase().includes(q)).map(d=>({label:`${d.id} · ${d.kind} · ${d.status}`,go:()=>openRecord(d.id)})),...data.inventory.filter(i=>i.item.toLowerCase().includes(q)).map(i=>({label:`${i.item} · Inventory · ${stockState(i)}`,go:()=>setNav("Inventory")}))]:[];
  const invoices=data.documents.filter(d=>d.kind==="invoice");const openInv=invoices.filter(d=>invStatus(d,documentTotal(d))!=="Paid");const overdue=openInv.filter(d=>/Overdue/.test(invStatus(d,documentTotal(d))));
  const revenue=invoices.reduce((a,d)=>a+documentTotal(d),0);const cogs=data.orders.filter(o=>o.invoiceId).reduce((a,o)=>a+orderTotals(o,data).lines.reduce((s,l)=>s+l.quantity*(data.itemRates.find(r=>r.item===l.item)?.cost||0),0),0);const net=revenue-cogs-(data.settings.monthlyExpenses||0);
  const running=data.workOrders.find(w=>w.status==="Running");const madeToday=data.workOrders.filter(w=>w.status==="Running"||w.status==="QC hold").reduce((a,w)=>a+w.good,0);const scrapToday=data.workOrders.filter(w=>w.status==="Running"||w.status==="QC hold").reduce((a,w)=>a+w.scrap,0);
  const lowRaw=data.inventory.filter(i=>i.kind==="raw"&&i.onHand<i.reorder);const lowFin=data.inventory.filter(i=>i.kind!=="raw"&&freeStock(i)<i.reorder*0.5);
  const openPOs=(data.purchaseOrders||[]).filter(p=>p.status==="Open");const poValue=openPOs.reduce((a,p)=>a+p.quantity*p.unitCost+p.freight+p.duty,0);
  const holds=data.workOrders.filter(w=>w.status==="QC hold");const dueMaint=(data.maintenance||[]).filter(m=>m.status==="Due");
  const approvals=[...data.orders.filter(o=>o.status==="Needs approval").map(o=>({name:`Approve pricing on ${o.id}`,detail:`${data.customers.find(c=>c.id===o.customerId)?.name} · ${usd(orderTotals(o,data).total)}`,go:()=>openRecord(o.id)})),...data.documents.filter(d=>d.status==="Awaiting approval").map(d=>({name:`Approve quote ${d.id}`,detail:`${data.customers.find(c=>c.id===d.customerId)?.name} · under the floor`,go:()=>openRecord(d.id)}))];
  const decisions=[...approvals,...data.workOrders.filter(w=>w.status==="Needs scheduling").map(w=>({name:`Schedule ${w.id}`,detail:`${num(w.quantity)} × ${w.item} · ${w.purpose}`,go:()=>openRecord(w.id)})),...holds.map(w=>({name:`Quality checks on ${w.id}`,detail:`${(w.qc||[]).filter(c=>c.result===null).length||"All"} checks waiting · ${w.item}`,go:()=>openRecord(w.id)})),...lowRaw.filter(r=>!r.onOrder).map(r=>({name:`Order ${r.item}`,detail:`${num(r.onHand)} on hand · reorder at ${num(r.reorder)}`,go:()=>setModal("po",r.item)})),...overdue.map(d=>({name:`Collect ${d.id}`,detail:`${data.customers.find(c=>c.id===d.customerId)?.name} · ${usd(documentTotal(d)-d.paid)} · ${invStatus(d,documentTotal(d))}`,go:()=>openRecord(d.id)})),...dueMaint.map(m=>({name:m.machine,detail:m.task+" · due "+m.due,go:()=>setNav("Maintenance")}))];
  const todaysSchedule=[...data.workOrders.filter(w=>["Running","Paused","Released","QC hold"].includes(w.status)).map(w=>({title:`${w.id} · ${w.line}`,detail:`${w.item} · ${num(w.good)} / ${num(w.quantity)}`,status:w.status,go:()=>openRecord(w.id)})),...data.orders.filter(o=>stageOf(o)===3).map(o=>({title:`Pack ${o.id}`,detail:`${data.customers.find(c=>c.id===o.customerId)?.name} · ${orderTotals(o,data).cases} boxes`,status:"Ready",go:()=>openRecord(o.id)})),...dueMaint.map(m=>({title:m.machine,detail:m.task,status:"Due",go:()=>setNav("Maintenance")}))];
  const dueThisWeek=data.orders.filter(o=>stageOf(o)<4);
  const ok=!overdue.length&&!holds.length&&!lowRaw.some(r=>!r.onOrder);
  const hr=new Date().getHours();const greet=hr<12?"Good morning":hr<17?"Good afternoon":"Good evening";
  return <>
    <div className="heading-row"><div><p className="eyebrow">Company command center</p><h1>{greet}, {data.settings.ownerName.split(" ")[0]}.</h1><p className="intro">Everything important across sales, production, inventory, quality, and cash.</p></div><div className="button-row"><button className="secondary" onClick={()=>downloadCsv(`makelogic-daily-${new Date().toISOString().slice(0,10)}.csv`,[["Metric","Value"],["Invoiced revenue",revenue],["Open receivables",openInv.reduce((a,d)=>a+documentTotal(d)-d.paid,0)],["Overdue",overdue.length],["Open orders",data.orders.filter(o=>stageOf(o)<6).length],["Running work order",running?.id||"none"],["Good bottles today",madeToday],["Scrap today",scrapToday],["Quality holds",holds.length],["Low materials",lowRaw.map(r=>r.item).join("; ")],["Open POs",openPOs.length]])}>Download daily report</button><button className="primary" onClick={()=>setModal("workorder")}>+ Work order</button></div></div>
    <div className="site-search"><span>⌕</span><input aria-label="Search the owner site" placeholder="Search the entire company..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch("")}>Clear</button>}{search&&<div className="search-results">{matches.length?matches.map(x=><button key={x.label} onClick={()=>{x.go();setSearch("")}}>{x.label}<span>Open →</span></button>):<p>No matches found.</p>}</div>}</div>
    {isLegacySeed(data)&&<div className="company-health" style={{marginBottom:12}}><span><i className="health-dot" style={{background:"#cf6822"}}/>This database still holds the Pure Alkaline starter records. <b>Load the EcoForm starter data</b> from Settings &amp; access when you&apos;re ready.</span><small><button className="link-button" onClick={()=>{if(confirm("Replace everything saved so far with the EcoForm starter data?")){commit(()=>seedData,"reset","Loaded EcoForm starter data");notify("EcoForm starter data loaded","Control center")}}}>Load now</button></small></div>}
    <div className="company-health"><span><i className="health-dot" style={ok?undefined:{background:"#cf6822"}}/>Company status: <b>{ok?"Operating normally":`${[overdue.length&&"overdue invoices",holds.length&&"quality holds",lowRaw.some(r=>!r.onOrder)&&"materials to order"].filter(Boolean).join(", ")}`}</b></span><small>Live · {new Date().toLocaleTimeString("en-US",{hour:"numeric",minute:"2-digit"})}</small></div>
    <div className="recap control-kpis"><Kpi label="Invoiced" value={usd(revenue)} note={`${invoices.length} invoices`}/><Kpi label="Cash to collect" value={usd(openInv.reduce((a,d)=>a+documentTotal(d)-d.paid,0))} note={overdue.length?`${usd(overdue.reduce((a,d)=>a+documentTotal(d)-d.paid,0))} overdue`:"nothing overdue"} warn={overdue.length>0}/><Kpi label="Net profit" value={usd(net)} note={revenue?`${Math.round(net/revenue*100)}% margin`:"no invoices yet"}/><Kpi label="Orders in progress" value={String(dueThisWeek.length)} note={`${data.orders.filter(o=>stageOf(o)===3).length} ready to ship`} warn={data.orders.some(o=>stageOf(o)===3)}/><Kpi label="Production today" value={num(madeToday)} note={`${madeToday+scrapToday?(scrapToday/(madeToday+scrapToday)*100).toFixed(1):"0.0"}% scrap`}/><Kpi label="Inventory alerts" value={String(lowRaw.length+lowFin.length)} note={`${lowRaw.filter(r=>!r.onOrder).length} need ordering`} warn={lowRaw.some(r=>!r.onOrder)}/></div>
    <section className="control-grid priority-row">
      <article className="panel control-panel"><div className="panel-title"><h2>Owner decisions {decisions.length>0&&<span className="count-badge">{decisions.length}</span>}</h2></div>{decisions.length?decisions.slice(0,8).map((d,i)=><Decision key={d.name} n={String(i+1)} name={d.name} detail={d.detail} onClick={d.go}/>):<p className="empty-list">Nothing waiting on you.</p>}</article>
      <article className="panel control-panel"><div className="panel-title"><h2>Today’s floor</h2><button onClick={()=>setNav("Production calendar")}>Calendar</button></div>{todaysSchedule.length?todaysSchedule.map(s=><MiniRow key={s.title} title={s.title} detail={s.detail} status={s.status} onClick={s.go}/>):<p className="empty-list">Nothing running. Release a work order to the floor.</p>}</article>
    </section>
    <section className="control-grid three-wide">
      <article className="panel control-panel"><div className="panel-title"><h2>Sales & customers</h2><button onClick={()=>setNav("Customers")}>Open sales</button></div><ControlMetric label="Open quotes" value={usd(data.documents.filter(d=>d.kind==="quote"&&!/Accepted/.test(d.status)).reduce((a,d)=>a+documentTotal(d),0))} onClick={()=>setNav("Quotes")}/><ControlMetric label="Awaiting approval" value={String(approvals.length)} danger={approvals.length>0} onClick={()=>setNav("Quotes")}/><ControlMetric label="Open leads" value={String(data.customers.filter(c=>c.kind==="lead").length)} onClick={()=>setNav("Leads")}/><ControlMetric label="Overdue customers" value={String(new Set(overdue.map(d=>d.customerId)).size)} danger={overdue.length>0} onClick={()=>setNav("Invoices")}/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Orders & shipping</h2><button onClick={()=>setNav("Orders")}>Open orders</button></div><ControlMetric label="New / confirmed" value={String(data.orders.filter(o=>stageOf(o)===0).length)} onClick={()=>setNav("Orders")}/><ControlMetric label="In production / QC" value={String(data.orders.filter(o=>stageOf(o)===1||stageOf(o)===2).length)} onClick={()=>setNav("Orders")}/><ControlMetric label="Ready to ship" value={String(data.orders.filter(o=>stageOf(o)===3).length)} danger={data.orders.some(o=>stageOf(o)===3)} onClick={()=>setNav("Orders")}/><ControlMetric label="Shipped, not invoiced" value={String(data.orders.filter(o=>stageOf(o)===4&&!o.invoiceId).length)} danger={data.orders.some(o=>stageOf(o)===4&&!o.invoiceId)} onClick={()=>setNav("Invoices")}/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Production</h2><button onClick={()=>setNav("Work orders")}>Open floor</button></div><ControlMetric label="Running now" value={running?`${running.id} · ${running.line}`:"Idle"} onClick={()=>running&&openRecord(running.id)}/><ControlMetric label="Completion" value={running?`${Math.round(running.good/running.quantity*100)}%`:"—"}/><ControlMetric label="Good bottles" value={num(madeToday)}/><ControlMetric label="Scrap rate" value={madeToday+scrapToday?`${(scrapToday/(madeToday+scrapToday)*100).toFixed(1)}%`:"—"}/></article>
    </section>
    <section className="control-grid three-wide">
      <article className="panel control-panel"><div className="panel-title"><h2>Inventory & purchasing</h2><button onClick={()=>setNav("Inventory")}>Inventory</button></div>{data.inventory.filter(i=>i.kind==="raw").slice(0,3).map(r=><StatusLine key={r.id} label={r.item} detail={r.usage?`using ${r.usage}`:`reorder at ${num(r.reorder)}`} state={r.onHand<r.reorder?(r.onOrder?`${num(r.onOrder)} on order`:"Order now"):"Good"} alert={r.onHand<r.reorder} onClick={()=>setNav("Inventory")}/>)}<StatusLine label="Open purchase orders" detail={`${openPOs.length} inbound`} state={usd(poValue)} onClick={()=>setNav("Purchasing")}/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Quality & maintenance</h2><button onClick={()=>setNav("Quality")}>View logs</button></div><StatusLine label="Quality holds" detail={holds.length?holds.map(w=>w.id).join(", "):"No active holds"} state={String(holds.length)} alert={holds.length>0} onClick={()=>setNav("Quality")}/><StatusLine label="Checks in progress" detail={running?`${running.id}`:"—"} state={running?`${(running.qc||[]).filter(c=>c.result!==null).length} of ${(running.qc||data.itemRates.find(r=>r.item===running.item)?.qcChecks||[]).length}`:"—"} onClick={()=>setNav("Quality")}/><StatusLine label="Maintenance due" detail={dueMaint[0]?dueMaint[0].machine:"Nothing due"} state={String(dueMaint.length)} alert={dueMaint.length>0} onClick={()=>setNav("Maintenance")}/><StatusLine label="Downtime this month" detail="Recorded on completed jobs" state={`${(data.maintenance||[]).reduce((a,m)=>a+(m.downtimeMin||0),0)} min`} onClick={()=>setNav("Maintenance")}/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Team activity</h2><button onClick={()=>setNav("Settings & access")}>Team view</button></div>{data.roles.filter(r=>!r.permissions.all).flatMap(r=>r.members.map(m=>({m,role:r.name}))).map(({m,role})=><StatusLine key={m} label={m} detail={role} state={/sales/i.test(role)?`${data.customers.filter(c=>c.rep===m&&c.kind==="lead").length} leads · ${data.orders.filter(o=>o.rep===m&&stageOf(o)<6).length} open orders`:running?`${running.id} · ${Math.round(running.good/running.quantity*100)}%`:"idle"} onClick={()=>setNav("Settings & access")}/>)}<StatusLine label="Recent activity" detail={data.activities[0]?.detail||"—"} state={data.activities[0]?.actor||""} onClick={()=>setNav("Reports")}/></article>
    </section>
    <section className="panel cash-strip"><div><span>Cash position</span><strong>{usd(data.settings.cashOnHand||0)}</strong><small>Enter in Settings</small></div><div><span>Receivables</span><strong>{usd(openInv.reduce((a,d)=>a+documentTotal(d)-d.paid,0))}</strong><small>{openInv.length} open invoices</small></div><div><span>Payables</span><strong>{usd(poValue)}</strong><small>Open purchase orders</small></div><div><span>Ready to invoice</span><strong>{usd(data.orders.filter(o=>stageOf(o)>=3&&!o.invoiceId).reduce((a,o)=>a+orderTotals(o,data).total,0))}</strong><small>Ready or shipped, not yet billed</small></div></section>
  </>;
}

// =============================================================== WORK ORDERS
export function WorkOrders(){
  const {data,openRecord,setModal}=useApp();
  return <><div className="heading-row"><div><p className="eyebrow">Production</p><h1>Work orders</h1><p className="intro">Make for a customer order or build bottles for stock. Orders that exceed free stock create one automatically.</p></div><button className="primary" onClick={()=>setModal("workorder")}>+ Create work order</button></div><div className="recap four"><Kpi label="Needs scheduling" value={String(data.workOrders.filter(x=>x.status==="Needs scheduling").length)} warn={data.workOrders.some(x=>x.status==="Needs scheduling")}/><Kpi label="Scheduled / released" value={String(data.workOrders.filter(x=>x.status==="Scheduled"||x.status==="Released").length)}/><Kpi label="Running" value={String(data.workOrders.filter(x=>x.status==="Running"||x.status==="Paused").length)}/><Kpi label="Quality hold" value={String(data.workOrders.filter(x=>x.status==="QC hold").length)} warn={data.workOrders.some(x=>x.status==="QC hold")}/></div>
    <article className="panel list">{[...data.workOrders].sort((a,b)=>(a.status==="Done"?1:0)-(b.status==="Done"?1:0)).map(x=>{const so=data.orders.find(o=>o.id===x.orderId);return <button key={x.id} onClick={()=>openRecord(x.id)}><span className="initials">{x.id.slice(-2)}</span><span><b>{x.id} · {x.item} · {num(x.quantity)}</b><small>{so?`${so.id} · ${data.customers.find(c=>c.id===so.customerId)?.name}`:x.purpose} · {x.line} · {x.date}</small></span><span>{x.status} · {Math.round(x.good/x.quantity*100)||0}% →</span></button>})}</article></>;
}

// =============================================================== ITEM RATES (live)
export function ItemRates(){
  const {data,setModal}=useApp();
  return <><div className="heading-row"><div><p className="eyebrow">Owner controlled</p><h1>Item rates</h1><p className="intro">Sales quotes start at list. Below the floor, or past the discount limit, the owner approves.</p></div><button className="primary" onClick={()=>setModal("rate")}>+ Add item rate</button></div><article className="panel rate-table"><div className="table-head"><span>Item</span><span>Price each · floor</span><span>Minimum</span><span>Sales discount</span></div>{data.itemRates.filter(r=>r.kind!=="raw").map(r=><button key={r.id} onClick={()=>setModal("rate",r.id)}><b>{r.item}</b><strong>{usd2(r.rate)} <small>· floor {usd2(r.floor??0)} · cost {usd2(r.cost||0)}</small></strong><span>{num(r.minimum)} bottles</span><span>Up to {r.discountLimit}%</span></button>)}</article></>;
}

// =============================================================== INVENTORY (live)
export function InventoryWorkspace(){
  const {data,setModal,commit,notify}=useApp();const fin=data.inventory.filter(i=>i.kind!=="raw");const raw=data.inventory.filter(i=>i.kind==="raw");
  const value=data.inventory.reduce((a,i)=>a+i.onHand*i.cost,0);const low=data.inventory.filter(i=>stockState(i)!=="Good");
  const inbound=(data.purchaseOrders||[]).filter(p=>p.status==="Open");
  const makeRun=(item:string)=>{setModal("workorder");notify(`Pick ${item} in the form`,"Work orders")};
  return <><div className="heading-row"><div><p className="eyebrow">Materials + finished goods</p><h1>Inventory</h1><p className="intro">Free = on hand minus promised to orders. Runs add finished goods and use materials; shipping removes them.</p></div><div className="button-row"><button className="secondary" onClick={()=>setModal("movement")}>Record movement</button><button className="primary" onClick={()=>setModal("inventory")}>+ Add inventory item</button></div></div>
    <div className="recap four"><Kpi label="Inventory value" value={usd(value)} note="at current cost"/><Kpi label="Low / short" value={String(low.length)} warn={low.length>0}/><Kpi label="Inbound POs" value={String(inbound.length)} note={inbound[0]?`next ${inbound[0].eta}`:""}/><Kpi label="Finished bottles free" value={num(fin.reduce((a,i)=>a+Math.max(0,freeStock(i)),0))}/></div>
    <h2 style={{margin:"18px 0 8px"}}>Finished goods</h2>
    <article className="panel ops-table"><div className="ops-head"><span>Item</span><span>On hand</span><span>Promised</span><span>Free</span><span>Status</span></div>{fin.map(i=>{const st=stockState(i);const covering=data.workOrders.find(w=>w.item===i.item&&w.status!=="Done");return <button key={i.id} className={st==="Good"?"":"alert"} onClick={()=>st==="Good"?setModal("movement"):covering?notify(`${covering.id} (${covering.status}) is already covering ${i.item}`,"Work orders"):makeRun(i.item)}><span>{i.item}</span><span>{num(i.onHand)}</span><span>{num(i.committed)}</span><span>{num(freeStock(i))}</span><span className={st==="Good"?"paid":"danger"}>{st}{covering&&st!=="Good"?` · ${covering.id}`:""}</span></button>})}</article>
    <h2 style={{margin:"18px 0 8px"}}>Raw materials &amp; packaging</h2>
    <article className="panel ops-table"><div className="ops-head"><span>Item</span><span>On hand</span><span>Reorder at</span><span>On order</span><span>Status</span></div>{raw.map(r=>{const st=stockState(r);return <button key={r.id} className={st==="Good"?"":"alert"} onClick={()=>st==="Good"||r.onOrder?setModal("movement"):setModal("po",r.item)}><span>{r.item}<small style={{display:"block",color:"#7b867f"}}>{r.usage?`${r.usage} · `:""}{usd2(r.cost)} each{r.supplier?` · ${r.supplier}`:""}</small></span><span>{num(r.onHand)}</span><span>{num(r.reorder)}</span><span>{r.onOrder?`${num(r.onOrder)} · ${r.eta}`:"—"}</span><span className={st==="Good"?"paid":"danger"}>{st==="Good"?"Good":r.onOrder?"Covered":"Order now"}</span></button>})}</article>
    <p className="link-warning" style={{marginTop:12}}>Counts wrong? <button className="link-button" onClick={()=>setModal("movement")}>Record a movement</button> to correct any line — every change is logged. Receiving a PO rolls freight and duty into the unit cost.{" "}<button className="link-button" onClick={()=>{commit(v=>({...v,inventory:v.inventory.map(i=>({...i,committed:v.orders.filter(o=>stageOf(o)<4&&o.status!=="Needs approval").reduce((a,o)=>a+(orderTotals(o,v).lines.find(l=>l.item===i.item)?.quantity||0),0)}))}),"inventory.recalc","Promised quantities recalculated");notify("Promised quantities recalculated from open orders","Inventory")}}>Recalculate promised</button></p></>;
}

// =============================================================== QUALITY (live)
export function QualityWorkspace(){
  const {data,openRecord,notify}=useApp();
  const active=data.workOrders.filter(w=>w.status==="QC hold"||w.status==="Running"||w.status==="Paused");
  const allChecks=active.flatMap(w=>(w.qc||data.itemRates.find(r=>r.item===w.item)?.qcChecks?.map(l=>({label:l,result:null as boolean|null}))||[]).map(c=>({...c,wo:w})));
  const doneChecks=allChecks.filter(c=>c.result!==null);const passed=data.workOrders.filter(w=>w.qcResult==="pass");const scrapped=data.workOrders.filter(w=>w.qcResult==="scrap");
  const good=data.workOrders.reduce((a,w)=>a+w.good,0);const scrap=data.workOrders.reduce((a,w)=>a+w.scrap,0);
  return <><div className="heading-row"><div><p className="eyebrow">Quality control</p><h1>Quality</h1><p className="intro">Every run gets its checklist. Nothing goes into stock until all checks pass.</p></div><button className="primary" onClick={()=>active[0]?openRecord(active[0].id):notify("No run is waiting for checks","Quality")}>+ Record quality check</button></div>
    <div className="recap four"><Kpi label="Checks today" value={`${doneChecks.length} of ${allChecks.length}`} warn={doneChecks.length<allChecks.length}/><Kpi label="Active holds" value={String(data.workOrders.filter(w=>w.status==="QC hold").length)} warn={data.workOrders.some(w=>w.status==="QC hold")}/><Kpi label="First-pass rate" value={passed.length+scrapped.length?`${Math.round(passed.length/(passed.length+scrapped.length)*100)}%`:"—"}/><Kpi label="Scrap rate" value={good+scrap?`${(scrap/(good+scrap)*100).toFixed(1)}%`:"—"}/></div>
    <div className="content-grid"><article className="panel"><h2>Checks waiting</h2>{allChecks.filter(c=>c.result===null).length?allChecks.filter(c=>c.result===null).map((c,i)=><CheckRow key={c.wo.id+c.label+i} title={`${c.wo.id} · ${c.label}`} detail={`${c.wo.line} · ${c.wo.item}${c.wo.status==="QC hold"?" · run finished":""}`} status={c.wo.status==="QC hold"?"Due now":"Before finish"} alert={c.wo.status==="QC hold"} onClick={()=>openRecord(c.wo.id)}/>):<p className="empty-list">No checks waiting.</p>}</article>
    <article className="panel"><h2>Recent quality activity</h2>{[...allChecks.filter(c=>c.result!==null).map(c=>({title:`${c.wo.id} · ${c.label}`,detail:c.wo.item,status:c.result?"Passed":"Failed",id:c.wo.id})),...passed.map(w=>({title:`${w.id} released`,detail:`${w.item} · ${num(w.good)} into stock`,status:"Passed",id:w.id})),...scrapped.map(w=>({title:`${w.id} scrapped`,detail:`${w.item} · re-run`,status:"Scrapped",id:w.id})),...data.workOrders.filter(w=>w.qcNote).map(w=>({title:`${w.id} note`,detail:w.qcNote!,status:"Note",id:w.id}))].slice(0,12).map((r,i)=><MiniRow key={r.title+i} title={r.title} detail={r.detail} status={r.status} onClick={()=>openRecord(r.id)}/>)}</article></div></>;
}

// =============================================================== MAINTENANCE (live)
export function MaintenanceWorkspace(){
  const {data,commit,notify,setModal}=useApp();const list=data.maintenance||[];
  const complete=(id:string)=>{const mins=window.prompt("Downtime in minutes (0 if none):","0");if(mins===null)return;commit(v=>({...v,maintenance:(v.maintenance||[]).map(m=>m.id===id?{...m,status:"Complete",downtimeMin:Number(mins)||0}:m)}),"maintenance.complete",`${id} complete`);notify("Maintenance marked complete","Maintenance")};
  return <><div className="heading-row"><div><p className="eyebrow">Equipment care</p><h1>Maintenance</h1><p className="intro">Preventive service, repair history, and downtime.</p></div><button className="primary" onClick={()=>setModal("maintenance")}>+ Schedule maintenance</button></div>
    <div className="recap four"><Kpi label="Due" value={String(list.filter(m=>m.status==="Due").length)} warn={list.some(m=>m.status==="Due")}/><Kpi label="Scheduled" value={String(list.filter(m=>m.status==="Scheduled").length)}/><Kpi label="Downtime recorded" value={`${list.reduce((a,m)=>a+(m.downtimeMin||0),0)} min`}/><Kpi label="Completed" value={String(list.filter(m=>m.status==="Complete").length)}/></div>
    <article className="panel list">{[...list].sort((a,b)=>(a.status==="Complete"?1:0)-(b.status==="Complete"?1:0)).map(m=><button key={m.id} onClick={()=>m.status!=="Complete"&&complete(m.id)}><span className="initials">⚙</span><span><b>{m.machine}</b><small>{m.task}</small></span><span><b>{m.status}{m.status!=="Complete"?" · tap to complete":""}</b><small>{m.due}{m.downtimeMin?` · ${m.downtimeMin} min downtime`:""}</small></span></button>)}{!list.length&&<p className="empty-list">Nothing scheduled.</p>}</article></>;
}

// =============================================================== PURCHASING (live)
export function PurchasingWorkspace(){
  const {data,setModal,openRecord}=useApp();const pos=data.purchaseOrders||[];const open=pos.filter(p=>p.status==="Open");const [nowMs]=useState(()=>Date.now());const yr=new Date(nowMs).getFullYear();
  const suggestions=data.inventory.filter(i=>i.kind==="raw"&&i.onHand<i.reorder&&!i.onOrder);
  return <><div className="heading-row"><div><p className="eyebrow">Inbound materials</p><h1>Purchasing</h1><p className="intro">Reorder suggestions, purchase orders, and landed cost on receipt.</p></div><button className="primary" onClick={()=>setModal("po")}>+ Create purchase order</button></div>
    <div className="recap four"><Kpi label="Open POs" value={String(open.length)}/><Kpi label="Open value" value={usd(open.reduce((a,p)=>a+p.quantity*p.unitCost+p.freight+p.duty,0))}/><Kpi label="Arriving this week" value={String(open.filter(p=>{const t=Date.parse(`${p.eta.replace(/\s*\(.*\)/,"")} ${yr}`);return !isNaN(t)&&t-nowMs<7*864e5}).length)}/><Kpi label="Reorder suggestions" value={String(suggestions.length)} warn={suggestions.length>0}/></div>
    <div className="content-grid"><article className="panel"><h2>Suggested purchases</h2>{suggestions.length?suggestions.map(r=><div className="purchase-row" key={r.id}><span><b>{r.item}</b><small>{num(r.onHand)} on hand · reorder at {num(r.reorder)}{r.usage?` · ${r.usage}`:""}</small></span><strong>{num(Math.max(r.reorder*2-r.onHand,r.reorder))}</strong><button onClick={()=>setModal("po",r.item)}>Create PO</button></div>):<p className="empty-list">Everything is above its reorder point or already on order.</p>}</article>
    <article className="panel"><h2>Purchase orders</h2>{pos.length?pos.map(p=><MiniRow key={p.id} title={`${p.id} · ${p.supplier}`} detail={`${num(p.quantity)} × ${p.item} · ${usd(p.quantity*p.unitCost+p.freight+p.duty)} · ETA ${p.eta}`} status={p.status} onClick={()=>openRecord(p.id)}/>):<p className="empty-list">No purchase orders yet.</p>}</article></div></>;
}

// =============================================================== P&L (COGS from item costs)
export function ProfitLoss(){
  const {data,commit,notify}=useApp();const invoices=data.documents.filter(x=>x.kind==="invoice");
  const revenue=invoices.reduce((s,x)=>s+documentTotal(x),0);
  const cogs=invoices.reduce((s,d)=>{const o=data.orders.find(o=>o.id===d.orderId);if(o)return s+orderTotals(o,data).lines.reduce((a,l)=>a+l.quantity*(data.itemRates.find(r=>r.item===l.item)?.cost||0),0);const r=data.itemRates.find(r=>d.item.startsWith(r.item));return s+(d.quantity||d.cases)*(r?.cost||0)},0);
  const gross=revenue-cogs;const expenses=data.settings.monthlyExpenses||0;const net=gross-expenses;const month=new Date().toLocaleDateString("en-US",{month:"long",year:"numeric"});
  const setExp=()=>{const v=window.prompt("Monthly operating expenses (rent, payroll, utilities, insurance):",String(expenses));if(v===null)return;commit(d=>({...d,settings:{...d.settings,monthlyExpenses:Number(v)||0}}),"settings.expenses","Operating expenses updated");notify("Operating expenses updated","Profit & loss")};
  const byItem=data.itemRates.filter(r=>r.kind!=="raw").map(r=>{const qty=invoices.reduce((a,d)=>{const o=data.orders.find(o=>o.id===d.orderId);const l=o?orderTotals(o,data).lines.find(l=>l.item===r.item):(d.item.startsWith(r.item)?{quantity:d.quantity||d.cases,rate:d.rate}:undefined);return a+(l?.quantity||0)},0);const rev=invoices.reduce((a,d)=>{const o=data.orders.find(o=>o.id===d.orderId);const l=o?orderTotals(o,data).lines.find(l=>l.item===r.item):(d.item.startsWith(r.item)?{quantity:d.quantity||d.cases,rate:d.rate}:undefined);return a+(l?l.quantity*l.rate:0)},0);return {item:r.item,qty,rev,margin:rev?(rev-qty*(r.cost||0))/rev:0}}).filter(x=>x.qty>0);
  return <><div className="heading-row"><div><p className="eyebrow">Owner financials</p><h1>Profit & loss</h1><p className="intro">{month} · Calculated from saved invoices and item costs</p></div><div className="button-row"><button className="secondary" onClick={setExp}>Set operating expenses</button><button className="secondary" onClick={()=>downloadCsv("makelogic-profit-loss.csv",[["Profit & loss",month],["Revenue",revenue],["Cost of goods sold",cogs],["Gross profit",gross],["Operating expenses",expenses],["Net profit",net],[],["Item","Bottles","Revenue","Margin"],...byItem.map(x=>[x.item,x.qty,x.rev,`${Math.round(x.margin*100)}%`])])}>Export report</button></div></div>
    <div className="recap four"><Kpi label="Revenue" value={usd(revenue)}/><Kpi label="Gross profit" value={usd(gross)} note={`${revenue?Math.round(gross/revenue*100):0}% margin`}/><Kpi label="Operating expenses" value={usd(expenses)}/><Kpi label="Net profit" value={usd(net)} note={`${revenue?Math.round(net/revenue*100):0}% margin`} warn={net<0}/></div>
    <article className="panel pl-table"><PlRow label="Invoice revenue" amount={usd(revenue)}/><PlRow label="Cost of goods sold (item cost × bottles)" amount={usd(cogs)}/><PlRow label="Gross profit" amount={usd(gross)} total/><PlRow label="Operating expenses" amount={usd(expenses)}/><PlRow label="Net profit" amount={usd(net)} grand/></article>
    {byItem.length>0&&<article className="panel" style={{marginTop:16}}><h2>Margin by product</h2>{byItem.map(x=><div className="margin-row" key={x.item}><div><span>{x.item} · {num(x.qty)} bottles · {usd(x.rev)}</span><b>{Math.round(x.margin*100)}%</b></div><div className="margin-track"><i style={{width:`${Math.max(0,Math.min(100,x.margin*100))}%`}}/></div></div>)}</article>}</>;
}

// =============================================================== REPORTS
export function ReportsWorkspace(){
  const {data,setNav}=useApp();const revenue=data.documents.filter(x=>x.kind==="invoice").reduce((s,x)=>s+documentTotal(x),0);const inventoryValue=Math.round(data.inventory.reduce((s,x)=>s+x.onHand*x.cost,0));const completed=data.workOrders.filter(x=>x.status==="Done").length;
  const byCustomer=data.customers.map(c=>[c.name,data.documents.filter(d=>d.kind==="invoice"&&d.customerId===c.id).reduce((a,d)=>a+documentTotal(d),0)] as [string,number]).sort((a,b)=>b[1]-a[1]);
  const exportAll=()=>downloadCsv("makelogic-company-report.csv",[["Metric","Value"],["Customers",data.customers.filter(x=>x.kind==="customer").length],["Open leads",data.customers.filter(x=>x.kind==="lead").length],["Invoice revenue",revenue],["Orders",data.orders.length],["Completed work orders",completed],["Inventory value",inventoryValue],[],["Customer","Invoiced"],...byCustomer]);
  return <><div className="heading-row"><div><p className="eyebrow">Company reporting</p><h1>Reports</h1><p className="intro">Live operational totals calculated from the same records used across the company.</p></div><button className="secondary" onClick={exportAll}>Export company report</button></div><div className="report-grid"><ReportCard title="Sales by customer" detail={byCustomer[0]?`Top: ${byCustomer[0][0]} · ${usd(byCustomer[0][1])}`:"Revenue by customer"} value={usd(revenue)} onClick={()=>setNav("Customers")}/><ReportCard title="Production performance" detail={`${data.workOrders.reduce((a,w)=>a+w.good,0).toLocaleString()} good · ${data.workOrders.reduce((a,w)=>a+w.scrap,0)} scrap all runs`} value={`${completed} completed`} onClick={()=>setNav("Work orders")}/><ReportCard title="Inventory valuation" detail="Materials and finished goods at current landed cost" value={usd(inventoryValue)} onClick={()=>setNav("Inventory")}/><ReportCard title="Order pipeline" detail={`${data.orders.filter(o=>stageOf(o)<6).length} open · ${data.orders.filter(o=>stageOf(o)===6).length} paid`} value={`${data.orders.length} orders`} onClick={()=>setNav("Orders")}/><ReportCard title="Quality" detail={`${data.workOrders.filter(w=>w.qcResult==="pass").length} passed · ${data.workOrders.filter(w=>w.qcResult==="scrap").length} scrapped`} value={`${data.workOrders.filter(w=>w.status==="QC hold").length} on hold`} onClick={()=>setNav("Quality")}/><ReportCard title="Activity log" detail="Every change, who made it, when" value={`${data.activities.length} events`} onClick={()=>downloadCsv("makelogic-activity.csv",[["When","Who","What","Detail"],...data.activities.map(a=>[a.createdAt,a.actor,a.title,a.detail])])}/></div></>;
}

// =============================================================== SETTINGS (Chris's, plus prices/shipping/company data)
export function SettingsWorkspace(){
  const {data,commit,notify}=useApp();const qb=data.settings.quickBooks;const[busy,setBusy]=useState(false);const[confirmReset,setConfirmReset]=useState(false);
  const patchQb=(change:Partial<typeof qb>)=>commit(v=>({...v,settings:{...v.settings,quickBooks:{...v.settings.quickBooks,...change}}}),"settings.quickbooks","QuickBooks settings updated");
  const connect=()=>{setBusy(true);setTimeout(()=>{patchQb({connected:true,realmId:"EcoForm-QBO",lastSync:"Connected · awaiting first sync"});setBusy(false);notify("QuickBooks connected — invoices and payments will mirror from here on","Settings & access")},700)};
  const sync=()=>{setBusy(true);setTimeout(()=>{commit(v=>({...v,documents:v.documents.map(d=>d.kind==="invoice"?{...d,qbSynced:true}:d),customers:v.customers.map(c=>({...c,qb:true})),settings:{...v.settings,quickBooks:{...v.settings.quickBooks,lastSync:new Date().toLocaleString(),conflicts:0}}}),"settings.quickbooks","QuickBooks sync");setBusy(false);notify("QuickBooks synchronization complete","Settings & access")},700)};
  const ship=data.settings.shipMethods||[];
  return <><p className="eyebrow">Owner administration</p><h1>Settings & access</h1><p className="intro">Company account, employee roles, warehouse access, pricing rules, shipping, and accounting synchronization.</p><MainAccountSettings/><RoleManager/>
    <div className="settings-layout"><section className="panel qb-panel"><div className="integration-head"><div className="qb-logo">qb</div><div><h2>QuickBooks Online</h2><p>{qb.connected?`Connected company · ${qb.realmId}`:"Connect your QuickBooks company to mirror customers, invoices and payments."}</p></div><span className={qb.connected?"connected":"not-connected"}>{qb.connected?"Connected":"Not connected"}</span></div>{!qb.connected?<button className="qb-connect" onClick={connect}>{busy?"Connecting…":"Connect to QuickBooks"}</button>:<><div className="sync-status"><span><i/>Last sync: {qb.lastSync}</span><button onClick={sync}>{busy?"Syncing…":"Sync now"}</button></div><h3>Two-way synchronization</h3><SyncToggle label="Customers" detail="Names, contacts, addresses, and terms" checked={qb.customers} change={()=>patchQb({customers:!qb.customers})}/><SyncToggle label="Invoices" detail="Amounts, due dates, and payment status" checked={qb.invoices} change={()=>patchQb({invoices:!qb.invoices})}/><SyncToggle label="Quotes / estimates" detail="Editable estimates in either system" checked={qb.quotes} change={()=>patchQb({quotes:!qb.quotes})}/><div className="sync-rules"><b>How this works</b><p>Invoices created here carry a QuickBooks flag and appear as synced; the live Intuit connection (OAuth + Invoice/Payment API) is wired at deploy time with your Intuit developer keys. Until then this panel records intent and keeps an audit entry per sync.</p></div><button className="disconnect" onClick={()=>patchQb({connected:false,realmId:"",lastSync:"Disconnected"})}>Disconnect QuickBooks</button></>}</section>
    <aside>
      <section className="panel settings-card"><h2>Pricing rules</h2><div className="form-grid"><label>Discount needing owner approval (%)<input type="number" value={data.settings.discountApproval??5} onChange={e=>commit(v=>({...v,settings:{...v.settings,discountApproval:Number(e.target.value)||0}}),"settings.discount","Discount limit")}/></label><label>Monthly operating expenses<input type="number" value={data.settings.monthlyExpenses||0} onChange={e=>commit(v=>({...v,settings:{...v.settings,monthlyExpenses:Number(e.target.value)||0}}),"settings.expenses","Expenses")}/></label><label>Cash on hand<input type="number" value={data.settings.cashOnHand||0} onChange={e=>commit(v=>({...v,settings:{...v.settings,cashOnHand:Number(e.target.value)||0}}),"settings.cash","Cash")}/></label></div></section>
      <section className="panel settings-card"><h2>Shipping options</h2>{ship.map(s=><div className="form-grid" key={s.id} style={{marginBottom:6}}><label>{s.name}<small style={{display:"block",color:"#7b867f"}}>{s.sub}</small></label><label>{s.perCase!=null?"Per box":"Flat rate"}<input type="number" step="0.1" value={s.perCase!=null?s.perCase:s.rate} onChange={e=>commit(v=>({...v,settings:{...v.settings,shipMethods:(v.settings.shipMethods||[]).map(x=>x.id===s.id?(x.perCase!=null?{...x,perCase:Number(e.target.value)||0}:{...x,rate:Number(e.target.value)||0}):x)}}),"settings.shipping",`${s.name} rate`)}/></label></div>)}<div className="form-grid"><label>Production lines (comma separated)<input value={(data.settings.lines||[]).join(", ")} onChange={e=>commit(v=>({...v,settings:{...v.settings,lines:e.target.value.split(",").map(x=>x.trim()).filter(Boolean)}}),"settings.lines","Lines")}/></label></div></section>
      <section className="panel settings-card"><h2>Company data</h2><SettingRow label="Audit log" value={`${data.activities.length} events`} onClick={()=>downloadCsv("makelogic-activity.csv",[["When","Who","What","Detail"],...data.activities.map(a=>[a.createdAt,a.actor,a.title,a.detail])])}/><SettingRow label="Export everything (JSON)" value="Download" onClick={()=>{const url=URL.createObjectURL(new Blob([JSON.stringify(data,null,2)],{type:"application/json"}));const a=document.createElement("a");a.href=url;a.download="makelogic-backup.json";a.click();URL.revokeObjectURL(url)}}/>{confirmReset?<div className="button-row"><button className="secondary" onClick={()=>{commit(()=>seedData,"reset","Loaded EcoForm starter data");setConfirmReset(false);notify("EcoForm starter data loaded","Settings & access")}}>Yes, replace everything</button><button className="cancel" onClick={()=>setConfirmReset(false)}>Cancel</button></div>:<SettingRow label="Load EcoForm starter data" value="Replaces all records" onClick={()=>setConfirmReset(true)}/>}</section>
    </aside></div></>;
}

export function MainAccountSettings(){const{data,commit,notify}=useApp();const[name,setName]=useState(data.settings.ownerName);const[email,setEmail]=useState(data.settings.ownerEmail);const[company,setCompany]=useState(data.settings.company);const token=data.settings.warehouseToken;const save=()=>{commit(v=>({...v,settings:{...v.settings,ownerName:name,ownerEmail:email,company}}),"settings.account","Owner account updated");notify("Main account settings saved","Settings & access")};const rotate=()=>{const next=`floor-${Math.random().toString(36).slice(2,8).toUpperCase()}`;commit(v=>({...v,settings:{...v.settings,warehouseToken:next}}),"warehouse.token.rotate","Warehouse access link rotated");notify("Warehouse link rotated — the old link no longer opens the floor","Settings & access")};const link=typeof window!=="undefined"?`${location.origin}${location.pathname}?floor=${token}#warehouse`:"";
  return <section className="panel main-account"><div className="panel-title"><div><h2>Main owner account</h2><p>Primary company administrator and recovery contact.</p></div><span className="owner-chip">Full access</span></div><div className="form-grid"><label>Owner name<input value={name} onChange={e=>setName(e.target.value)}/></label><label>Owner email<input value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Company name<input value={company} onChange={e=>setCompany(e.target.value)}/></label><label>Warehouse private key<input value={token} readOnly/></label></div><div className="button-row"><button className="secondary" onClick={rotate}>Rotate warehouse link</button><button className="secondary" onClick={()=>{navigator.clipboard.writeText(link);notify("Warehouse link copied","Settings & access")}}>Copy warehouse link</button><button className="primary" onClick={save}>Save main account</button></div><p className="link-warning">The floor tablet opens <code>{link}</code>. Anyone with the key gets the warehouse screens only.</p></section>}

export function RoleManager(){const{data,commit,notify}=useApp();const[expanded,setExpanded]=useState(data.roles[1]?.id||"");const setPermission=(roleId:string,key:string,value:"none"|"view"|"edit")=>commit(v=>({...v,roles:v.roles.map(r=>r.id===roleId?{...r,permissions:{...r.permissions,[key]:value}}:r)}),"roles.update",`Permissions updated for ${roleId}`);const keys=["crm","sales","calendar","operations","financials","settings"];
  const rename=(id:string)=>{const r=data.roles.find(x=>x.id===id)!;const n=window.prompt("Role name:",r.name);if(n)commit(v=>({...v,roles:v.roles.map(x=>x.id===id?{...x,name:n}:x)}),"roles.update","Role renamed")};
  const members=(id:string)=>{const r=data.roles.find(x=>x.id===id)!;const n=window.prompt("People in this role (comma separated):",r.members.join(", "));if(n!==null)commit(v=>({...v,roles:v.roles.map(x=>x.id===id?{...x,members:n.split(",").map(s=>s.trim()).filter(Boolean)}:x)}),"roles.update","Members updated")};
  return <section className="panel role-manager"><div className="panel-title"><div><h2>Employee roles & permissions</h2><p>Owner access is fixed. Sales and warehouse access can be changed by job title.</p></div><button className="primary" onClick={()=>{const id=`r${Date.now()}`;commit(v=>({...v,roles:[...v.roles,{id,name:"New employee role",members:[],permissions:{crm:"view"}}]}),"roles.create","New role created");setExpanded(id)}}>+ Add role</button></div><div className="role-list">{data.roles.map(role=><div className="role-block" key={role.id}><button className="role-summary" onClick={()=>setExpanded(expanded===role.id?"":role.id)}><span><b>{role.name}</b><small>{role.members.join(", ")||"No employees assigned"}</small></span><span>{role.permissions.all?"All company access":"Custom access"}</span><i>{expanded===role.id?"⌃":"⌄"}</i></button>{expanded===role.id&&<div className="permission-grid">{keys.map(key=><label key={key}><span>{key[0].toUpperCase()+key.slice(1)}</span><select disabled={!!role.permissions.all} value={role.permissions.all||role.permissions[key]||"none"} onChange={e=>setPermission(role.id,key,e.target.value as "none"|"view"|"edit")}><option value="none">None</option><option value="view">View</option><option value="edit">Edit</option></select></label>)}<div className="role-actions"><button className="secondary" onClick={()=>rename(role.id)}>Rename</button><button className="secondary" onClick={()=>members(role.id)}>Edit people</button>{!role.permissions.all&&<button className="secondary" onClick={()=>{if(confirm(`Remove the ${role.name} role?`))commit(v=>({...v,roles:v.roles.filter(r=>r.id!==role.id)}),"roles.delete",`${role.name} removed`)}}>Remove role</button>}<button className="primary" onClick={()=>notify(`Permissions saved — ${role.name}`,"Settings & access")}>Save permissions</button></div></div>}</div>)}</div></section>}

