"use client";
import { useState } from "react";

type Role="sales"|"owner"|"floor";
type Modal="quote"|"invoice"|"lead"|"import"|"workorder"|"rate"|null;
const salesNav=["Dashboard","Leads","Customers","Quotes","Invoices","Orders"];
const floorNav=["Production","Pack orders"];
const customers=["Martin Supply","North Point Labs","Atlas Chemical"];
const orders=[
  {id:"#2051",customer:"Atlas Chemical",item:"8 cases · 16 oz Clear",due:"Today",status:"Ready",money:"Paid"},
  {id:"#2050",customer:"North Point Labs",item:"24 cases · 12 oz Amber",due:"Friday",status:"In production",money:"$6,480 due"},
  {id:"#2049",customer:"Martin Supply",item:"12 cases · 32 oz Handleware",due:"Sep 8",status:"Confirmed",money:"$3,240 overdue"},
  {id:"#2048",customer:"Beacon Labs",item:"6 cases · 16 oz Clear",due:"Sep 10",status:"Shipped",money:"Paid"},
];

export default function Home(){
  const[role,setRole]=useState<Role>("sales");
  const[nav,setNav]=useState("Dashboard");
  const[modal,setModal]=useState<Modal>(null);
  const[toast,setToast]=useState("");
  const[unit,setUnit]=useState<"bottles"|"boxes">("boxes");
  const[amount,setAmount]=useState("1");
  const[goodCount,setGoodCount]=useState(1250);
  const notify=(text:string)=>{setToast(text);setTimeout(()=>setToast(""),2800)};
  const changeRole=(next:Role)=>{setRole(next);setNav(next==="sales"?"Dashboard":next==="owner"?"Control center":"Production")};
  return <>
    <main className={role==="floor"?"floor-shell":"app-shell"}>
      <header className={role==="floor"?"floor-top":"topbar"}><Logo/><RoleBar role={role} setRole={changeRole}/><div className="avatar">{role==="sales"?"DG":role==="owner"?"CG":"WH"}</div></header>
      <div className={role==="floor"?"floor-app":"app-layout"}>
        <SideNav role={role} nav={nav} setNav={setNav}/>
        <section className={role==="floor"?"floor-workspace":"workspace"}>
          {role==="sales"?<SalesView nav={nav} setModal={setModal}/>:role==="owner"?<OwnerView nav={nav} setModal={setModal}/>:<FloorView nav={nav} unit={unit} setUnit={setUnit} amount={amount} setAmount={setAmount} goodCount={goodCount} setGoodCount={setGoodCount} notify={notify}/>} 
        </section>
      </div>
    </main>
    {modal&&<ActionModal type={modal} close={()=>setModal(null)} complete={m=>{setModal(null);notify(m)}}/>}
    {toast&&<Toast text={toast}/>} 
  </>;
}

function Logo(){return <div className="logo">Make<span>Logic</span></div>}
function RoleBar({role,setRole}:{role:Role;setRole:(r:Role)=>void}){return <nav className="rolebar" aria-label="Preview role">{(["sales","owner","floor"] as Role[]).map(r=><button key={r} onClick={()=>setRole(r)} className={role===r?"active":""}>{r==="sales"?"Sales Rep":r==="owner"?"Owner":"Warehouse"}</button>)}</nav>}
function SideNav({role,nav,setNav}:{role:Role;nav:string;setNav:(v:string)=>void}){
  if(role==="owner")return <OwnerNavigation nav={nav} setNav={setNav}/>;
  const items=role==="sales"?salesNav:floorNav;
  return <aside className={role==="floor"?"floor-side":"sidebar"}><small>{role==="sales"?"SALES WORKSPACE":"WAREHOUSE FLOOR"}</small>{items.map(x=><button key={x} onClick={()=>setNav(x)} className={nav===x?"selected":""}>{x}</button>)}</aside>
}
const ownerGroups=[
  {label:"Sales & customers",items:["Customers","Leads","Orders","Invoices","Quotes"]},
  {label:"Production",items:["Work orders","Production calendar","Quality","Maintenance"]},
  {label:"Inventory & purchasing",items:["Inventory","Purchasing","Item rates"]},
  {label:"Financials",items:["Profit & loss","Reports"]},
  {label:"Administration",items:["Settings & access"]},
];
function OwnerNavigation({nav,setNav}:{nav:string;setNav:(v:string)=>void}){return <aside className="sidebar owner-sidebar"><small>OWNER WORKSPACE</small><button onClick={()=>setNav("Control center")} className={`owner-home ${nav==="Control center"?"selected":""}`}><span>⌂</span>Control center</button><div className="owner-nav-groups">{ownerGroups.map((group,index)=>{const active=group.items.includes(nav);return <details key={group.label} open={active||index===0}><summary><span>{group.label}</span><i>⌄</i></summary><div>{group.items.map(item=><button key={item} onClick={()=>setNav(item)} className={nav===item?"selected":""}>{item}</button>)}</div></details>})}</div></aside>}

function SalesView({nav,setModal}:{nav:string;setModal:(m:Modal)=>void}){
  if(nav==="Leads")return <Leads setModal={setModal}/>;
  if(nav==="Customers")return <Customers setModal={setModal}/>;
  if(nav==="Quotes")return <DocList title="Quotes" action="Create quote" onAction={()=>setModal("quote")} rows={["Q-108 · Martin Supply · $4,180 · Draft","Q-107 · Hudson Labs · $8,940 · Sent","Q-106 · Westfield Supply · $2,760 · Accepted"]}/>;
  if(nav==="Invoices")return <DocList title="Invoices" action="Create invoice" onAction={()=>setModal("invoice")} rows={["INV-392 · Martin Supply · $3,240 · Overdue","INV-391 · North Point Labs · $6,480 · Due Friday","INV-390 · Atlas Chemical · $2,160 · Paid"]}/>;
  if(nav==="Orders")return <OrdersTable compact/>;
  return <SalesDashboard setModal={setModal}/>;
}

function SalesDashboard({setModal}:{setModal:(m:Modal)=>void}){const[search,setSearch]=useState("");const records=["Martin Supply · Customer · $3,240 overdue","North Point Labs · Customer · Order #2050","Atlas Chemical · Customer · Paid","Hudson Labs · Lead · Call today","Westfield Supply · Lead · Quote Q-106","INV-392 · Martin Supply · Invoice","#2051 · Atlas Chemical · Order"];
  const matches=search.trim()?records.filter(x=>x.toLowerCase().includes(search.toLowerCase())):[];
  return <><div className="heading-row"><div><p className="eyebrow">Tuesday, September 1</p><h1>Sales at a glance</h1><p className="intro">Customers, money, and orders that need attention.</p></div><button className="primary" onClick={()=>setModal("quote")}>+ New quote</button></div><div className="site-search"><span>⌕</span><input aria-label="Search the sales site" placeholder="Search customers, leads, orders, quotes, or invoices..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch("")}>Clear</button>}{search&&<div className="search-results">{matches.length?matches.map(x=><button key={x}>{x}<span>Open →</span></button>):<p>No matches found.</p>}</div>}</div><div className="recap four"><Kpi label="Open leads" value="7" note="2 need follow-up"/><Kpi label="Quotes open" value="$15,880" note="3 awaiting reply"/><Kpi label="Customer balances" value="$9,720" note="$3,240 overdue" warn/><Kpi label="Sales this month" value="$42,680" note="18 orders"/></div><div className="content-grid sales-grid"><article className="panel"><div className="panel-title"><h2>Money to collect</h2><button>View invoices</button></div><MoneyRow customer="Martin Supply" amount="$3,240" detail="12 days overdue" danger/><MoneyRow customer="North Point Labs" amount="$6,480" detail="Due Friday"/><MoneyRow customer="Atlas Chemical" amount="Paid" detail="INV-390" good/></article><article className="panel"><div className="panel-title"><h2>Shared leads</h2><button onClick={()=>setModal("lead")}>+ Add lead</button></div><MiniRow title="Hudson Labs" detail="Call today · Assigned to Sarah" status="Hot"/><MiniRow title="Westfield Supply" detail="Quote sent · Assigned to Dad" status="Waiting"/><MiniRow title="Greenline Co." detail="New website lead · Unassigned" status="New"/></article></div><article className="panel dashboard-orders"><div className="panel-title"><h2>Orders moving now</h2><button>See all orders</button></div><OrdersTable compact embedded/></article></>}

function Leads({setModal}:{setModal:(m:Modal)=>void}){return <><div className="heading-row"><div><p className="eyebrow">Shared by both reps</p><h1>Leads</h1><p className="intro">Every rep sees the same notes, owner, and next step.</p></div><button className="primary" onClick={()=>setModal("lead")}>+ Add lead</button></div><div className="recap"><Kpi label="New" value="3"/><Kpi label="Follow up today" value="2" warn/><Kpi label="Quotes sent" value="2"/></div><article className="panel list"><LeadRow company="Hudson Labs" contact="Maria Chen · 215-555-0184" owner="Sarah" next="Call today"/><LeadRow company="Westfield Supply" contact="Tom Adams · tom@westfield.test" owner="Dad" next="Quote sent"/><LeadRow company="Greenline Co." contact="Website inquiry · 16 oz bottles" owner="Unassigned" next="Reply today"/></article></>}
function Customers({setModal}:{setModal:(m:Modal)=>void}){const[search,setSearch]=useState("");const filtered=customers.filter(x=>x.toLowerCase().includes(search.toLowerCase()));return <><div className="heading-row"><div><p className="eyebrow">Sales</p><h1>Customers</h1><p className="intro">Import a spreadsheet or add one company at a time.</p></div><div className="button-row"><button className="secondary" onClick={()=>setModal("import")}>Import CSV</button><button className="primary" onClick={()=>setModal("lead")}>+ Add customer</button></div></div><div className="customer-search"><span>⌕</span><input aria-label="Search customers" placeholder="Search by customer name..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch("")}>Clear</button>}</div><p className="result-count">{filtered.length} {filtered.length===1?"customer":"customers"}</p><article className="panel list">{filtered.length?filtered.map(x=>{const i=customers.indexOf(x);return <button key={x}><span className="initials">{x.split(" ").map(a=>a[0]).join("")}</span><b>{x}</b><span>{i===0?"$3,240 overdue":i===1?"$6,480 due":"Paid"} →</span></button>}):<div className="empty-list">No customers match “{search}”.</div>}</article></>}
function DocList({title,action,onAction,rows}:{title:string;action:string;onAction:()=>void;rows:string[]}){return <><div className="heading-row"><div><p className="eyebrow">Sales documents</p><h1>{title}</h1><p className="intro">Pricing comes from the owner’s item rate list. Reps can add approved discounts and shipping.</p></div><button className="primary" onClick={onAction}>{action}</button></div><article className="panel list">{rows.map((r,i)=><button key={r}><span className="initials">{i+1}</span><b>{r}</b><span>Open →</span></button>)}</article></>}

function OwnerView({nav,setModal}:{nav:string;setModal:(m:Modal)=>void}){
  if(nav==="Customers")return <OwnerCustomers setModal={setModal}/>;
  if(nav==="Leads")return <OwnerLeads setModal={setModal}/>;
  if(nav==="Orders")return <OwnerOrders/>;
  if(nav==="Invoices")return <OwnerDocuments title="Invoices" action="Create invoice" onAction={()=>setModal("invoice")} rows={["INV-392 · Martin Supply · $3,240 · Overdue","INV-391 · North Point Labs · $6,480 · Due Friday","INV-390 · Atlas Chemical · $2,160 · Paid"]}/>;
  if(nav==="Quotes")return <OwnerDocuments title="Quotes" action="Create quote" onAction={()=>setModal("quote")} rows={["Q-108 · Martin Supply · $4,180 · Draft","Q-107 · Hudson Labs · $8,940 · Sent","Q-106 · Westfield Supply · $2,760 · Accepted"]}/>;
  if(nav==="Work orders")return <WorkOrders setModal={setModal}/>;
  if(nav==="Production calendar")return <ProductionCalendar/>;
  if(nav==="Item rates")return <ItemRates setModal={setModal}/>;
  if(nav==="Profit & loss")return <ProfitLoss/>;
  if(nav!=="Control center")return <SimpleOwner title={nav}/>;
  return <OwnerControlCenter setModal={setModal}/>;
}
function OwnerControlCenter({setModal}:{setModal:(m:Modal)=>void}){
  const[search,setSearch]=useState("");
  const records=["Martin Supply · Customer · $3,240 overdue","North Point Labs · Customer · Order #2050","Atlas Chemical · Customer · Paid","#2051 · Atlas Chemical · Ready","WO-1048 · North Point Labs · Running","WO-1049 · Build in-house stock","Blue caps · Inventory · Low","16 oz Clear Bottle · Item rate $54/case","Blow molder · Maintenance due tomorrow"];
  const matches=search.trim()?records.filter(x=>x.toLowerCase().includes(search.toLowerCase())):[];
  return <>
    <div className="heading-row"><div><p className="eyebrow">Company command center</p><h1>Good afternoon, Christopher.</h1><p className="intro">Everything important across sales, production, inventory, quality, and cash.</p></div><div className="button-row"><button className="secondary">Download daily report</button><button className="primary" onClick={()=>setModal("workorder")}>+ Work order</button></div></div>
    <div className="site-search"><span>⌕</span><input aria-label="Search the owner site" placeholder="Search the entire company..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch("")}>Clear</button>}{search&&<div className="search-results">{matches.length?matches.map(x=><button key={x}>{x}<span>Open →</span></button>):<p>No matches found.</p>}</div>}</div>
    <div className="company-health"><span><i className="health-dot"/>Company status: <b>Operating normally</b></span><small>Last updated 1:42 PM</small></div>
    <div className="recap control-kpis"><Kpi label="Sales this month" value="$82,460" note="+$8,120 vs August"/><Kpi label="Cash to collect" value="$9,720" note="$3,240 overdue" warn/><Kpi label="Net profit" value="$18,090" note="21.9% margin"/><Kpi label="Orders due this week" value="6" note="2 due today" warn/><Kpi label="Production today" value="7,250" note="bottles completed"/><Kpi label="Inventory alerts" value="2" note="1 needs ordering" warn/></div>
    <section className="control-grid priority-row">
      <article className="panel control-panel"><div className="panel-title"><h2>Owner decisions <span className="count-badge">4</span></h2><button>View all</button></div><Decision n="1" name="Approve tomorrow’s bottle run" detail="Line 1 · 6,000 × 16 oz bottles"/><Decision n="2" name="Order blue caps" detail="Six days remaining · Suggested 12,000"/><Decision n="3" name="Review Martin Supply balance" detail="$3,240 · 12 days overdue"/><Decision n="4" name="Set rate for new 24 oz bottle" detail="Sales is waiting to quote"/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Today’s schedule</h2><button>Calendar</button></div><MiniRow title="8:00 AM · WO-1048" detail="North Point · 16 oz Clear" status="Running"/><MiniRow title="1:00 PM · WO-1049" detail="12 oz Amber · Build stock" status="Next"/><MiniRow title="3:30 PM · Pack #2051" detail="Atlas Chemical · 8 cases" status="Ready"/><MiniRow title="4:15 PM · Line clean" detail="Line 1 · About 30 minutes" status="Planned"/></article>
    </section>
    <section className="control-grid three-wide">
      <article className="panel control-panel"><div className="panel-title"><h2>Sales & customers</h2><button>Open sales</button></div><ControlMetric label="Open pipeline" value="$28,400"/><ControlMetric label="Quotes awaiting reply" value="2"/><ControlMetric label="New leads" value="3"/><ControlMetric label="Overdue customers" value="1" danger/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Orders & shipping</h2><button>Open orders</button></div><ControlMetric label="Due today" value="2" danger/><ControlMetric label="Ready to pack" value="1"/><ControlMetric label="Ready to ship" value="4"/><ControlMetric label="Shipped this week" value="9"/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Production</h2><button>Open floor</button></div><ControlMetric label="Running now" value="WO-1048"/><ControlMetric label="Today’s completion" value="68%"/><ControlMetric label="Good bottles" value="7,250"/><ControlMetric label="Scrap rate" value="1.8%"/></article>
    </section>
    <section className="control-grid three-wide">
      <article className="panel control-panel"><div className="panel-title"><h2>Inventory & purchasing</h2><button>Inventory</button></div><StatusLine label="Blue caps" detail="6 days left" state="Order soon" alert/><StatusLine label="Clear preforms" detail="18 days left" state="Good"/><StatusLine label="Open purchase orders" detail="2 inbound" state="$14,280"/><StatusLine label="Next delivery" detail="Resin · Thursday" state="On time"/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Quality & maintenance</h2><button>View logs</button></div><StatusLine label="Quality holds" detail="No active holds" state="0"/><StatusLine label="Checks completed" detail="Today" state="3 of 4" alert/><StatusLine label="Blow molder service" detail="Due tomorrow" state="Schedule" alert/><StatusLine label="Last downtime" detail="18 days ago" state="42 min"/></article>
      <article className="panel control-panel"><div className="panel-title"><h2>Team activity</h2><button>Team view</button></div><StatusLine label="Dad" detail="Sales" state="2 follow-ups" alert/><StatusLine label="Sarah" detail="Sales" state="1 quote due"/><StatusLine label="Warehouse" detail="WO-1048 running" state="68%"/><StatusLine label="Owner tasks" detail="Decisions waiting" state="4" alert/></article>
    </section>
    <section className="panel cash-strip"><div><span>Cash position</span><strong>$64,280</strong><small>Bank balance</small></div><div><span>Receivables</span><strong>$9,720</strong><small>Expected within 30 days</small></div><div><span>Payables</span><strong>$14,280</strong><small>Open purchase orders</small></div><div><span>Projected month end</span><strong>$72,600</strong><small>Based on scheduled work</small></div></section>
  </>
}
function ControlMetric({label,value,danger}:{label:string;value:string;danger?:boolean}){return <div className="control-metric"><span>{label}</span><strong className={danger?"danger":""}>{value}</strong></div>}
function StatusLine({label,detail,state,alert}:{label:string;detail:string;state:string;alert?:boolean}){return <div className="status-line"><span><b>{label}</b><small>{detail}</small></span><em className={alert?"alert":""}>{state}</em></div>}
function OwnerCustomers({setModal}:{setModal:(m:Modal)=>void}){const[search,setSearch]=useState("");const all=[...customers,"Beacon Labs"];const filtered=all.filter(x=>x.toLowerCase().includes(search.toLowerCase()));return <><div className="heading-row"><div><p className="eyebrow">Owner directory</p><h1>Customers</h1><p className="intro">See customer balances, open orders, sales ownership, and account details.</p></div><div className="button-row"><button className="secondary" onClick={()=>setModal("import")}>Import CSV</button><button className="primary" onClick={()=>setModal("lead")}>+ Add customer</button></div></div><div className="customer-search"><span>⌕</span><input aria-label="Search owner customers" placeholder="Search by customer name..." value={search} onChange={e=>setSearch(e.target.value)}/>{search&&<button onClick={()=>setSearch("")}>Clear</button>}</div><p className="result-count">{filtered.length} {filtered.length===1?"customer":"customers"}</p><article className="panel list">{filtered.length?filtered.map((x,i)=><button key={x}><span className="initials">{x.split(" ").map(a=>a[0]).join("")}</span><span><b>{x}</b><small>{i%2===0?"Sales owner: Dad":"Sales owner: Sarah"}</small></span><span><b>{x==="Martin Supply"?"$3,240 overdue":x==="North Point Labs"?"$6,480 due":"Paid"}</b><small>{x==="Beacon Labs"?"No open orders":"1 open order"}</small></span></button>):<div className="empty-list">No customers match “{search}”.</div>}</article></>}
function OwnerLeads({setModal}:{setModal:(m:Modal)=>void}){return <><div className="heading-row"><div><p className="eyebrow">All sales activity</p><h1>Leads</h1><p className="intro">See every lead entered by either rep, who owns it, and the next action.</p></div><button className="primary" onClick={()=>setModal("lead")}>+ Add lead</button></div><div className="recap four"><Kpi label="New" value="3"/><Kpi label="Follow up today" value="2" warn/><Kpi label="Quotes sent" value="2"/><Kpi label="Potential value" value="$28,400"/></div><article className="panel list"><LeadRow company="Hudson Labs" contact="Maria Chen · 215-555-0184" owner="Sarah" next="Call today"/><LeadRow company="Westfield Supply" contact="Tom Adams · tom@westfield.test" owner="Dad" next="Quote sent"/><LeadRow company="Greenline Co." contact="Website inquiry · 16 oz bottles" owner="Unassigned" next="Reply today"/></article></>}
function OwnerDocuments({title,action,onAction,rows}:{title:string;action:string;onAction:()=>void;rows:string[]}){return <><div className="heading-row"><div><p className="eyebrow">Owner financial documents</p><h1>{title}</h1><p className="intro">Review documents from both sales reps, payment status, pricing, discounts, and shipping.</p></div><button className="primary" onClick={onAction}>{action}</button></div><div className="recap"><Kpi label={title==="Invoices"?"Outstanding":"Open quotes"} value={title==="Invoices"?"$9,720":"$15,880"} warn/><Kpi label={title==="Invoices"?"Paid this month":"Accepted this month"} value={title==="Invoices"?"$36,200":"$24,640"}/><Kpi label={title==="Invoices"?"Overdue":"Awaiting reply"} value={title==="Invoices"?"1":"2"}/></div><article className="panel list">{rows.map((r,i)=><button key={r}><span className="initials">{i+1}</span><b>{r}</b><span>Open →</span></button>)}</article></>}
function ProfitLoss(){return <><div className="heading-row"><div><p className="eyebrow">Owner financials</p><h1>Profit & loss</h1><p className="intro">September 1–30, 2026 · Accrual basis</p></div><div className="button-row"><button className="secondary">This month ▾</button><button className="secondary">Export report</button></div></div><div className="recap four"><Kpi label="Revenue" value="$82,460" note="+$8,120 vs August"/><Kpi label="Gross profit" value="$39,470" note="47.9% margin"/><Kpi label="Operating expenses" value="$21,380" note="26.0% of revenue"/><Kpi label="Net profit" value="$18,090" note="21.9% margin"/></div><div className="pl-layout"><article className="panel pl-table"><div className="pl-heading"><b>Income</b><span>September</span></div><PlRow label="Bottle sales" amount="$76,240"/><PlRow label="Shipping income" amount="$4,980"/><PlRow label="Setup and mold charges" amount="$1,240"/><PlRow label="Total revenue" amount="$82,460" total/><div className="pl-heading"><b>Cost of goods sold</b><span></span></div><PlRow label="Preforms and resin" amount="$25,180"/><PlRow label="Caps, labels, and cartons" amount="$9,460"/><PlRow label="Direct production labor" amount="$6,850"/><PlRow label="Freight-in" amount="$1,500"/><PlRow label="Total cost of goods" amount="$42,990" total/><PlRow label="Gross profit" amount="$39,470" grand/><div className="pl-heading"><b>Operating expenses</b><span></span></div><PlRow label="Payroll and benefits" amount="$11,600"/><PlRow label="Rent and utilities" amount="$4,220"/><PlRow label="Machine maintenance" amount="$2,180"/><PlRow label="Insurance and office" amount="$1,740"/><PlRow label="Sales and delivery" amount="$1,640"/><PlRow label="Total operating expenses" amount="$21,380" total/><PlRow label="Net profit" amount="$18,090" grand/></article><aside className="panel margin-panel"><h2>Where profit comes from</h2><MarginBar label="16 oz Clear" value="54%" width="54%"/><MarginBar label="12 oz Amber" value="49%" width="49%"/><MarginBar label="32 oz Handleware" value="41%" width="41%"/><div className="owner-note"><b>Owner note</b><p>Handleware margin is below the company average. Review its item rate before the next large quote.</p></div></aside></div></>}
function PlRow({label,amount,total,grand}:{label:string;amount:string;total?:boolean;grand?:boolean}){return <div className={`pl-row ${total?"total":""} ${grand?"grand":""}`}><span>{label}</span><strong>{amount}</strong></div>}
function MarginBar({label,value,width}:{label:string;value:string;width:string}){return <div className="margin-row"><div><span>{label}</span><b>{value}</b></div><div className="margin-track"><i style={{width}}/></div></div>}
function OwnerOrders(){return <><p className="eyebrow">Owner overview</p><h1>Orders</h1><p className="intro">Customer orders from sale through production, packing, payment, and shipping.</p><div className="recap four"><Kpi label="Due now" value="2" warn/><Kpi label="Ready" value="4"/><Kpi label="Shipped" value="9"/><Kpi label="Awaiting payment" value="$9,720" warn/></div><article className="panel"><OrdersTable/></article></>}
function WorkOrders({setModal}:{setModal:(m:Modal)=>void}){return <><div className="heading-row"><div><p className="eyebrow">Production</p><h1>Work orders</h1><p className="intro">Make for a customer order or build bottles for in-house stock.</p></div><button className="primary" onClick={()=>setModal("workorder")}>+ Create work order</button></div><div className="recap"><Kpi label="Scheduled" value="5"/><Kpi label="Running" value="1"/><Kpi label="Completed this week" value="7"/></div><article className="panel list"><WorkRow id="WO-1048" item="16 oz Clear · 6,000" purpose="Customer order #2050" status="Scheduled"/><WorkRow id="WO-1049" item="12 oz Amber · 4,000" purpose="Build in-house stock" status="Scheduled"/><WorkRow id="WO-1047" item="16 oz Clear · 8,000" purpose="Build in-house stock" status="Running"/></article></>}
function ProductionCalendar(){return <><p className="eyebrow">Orders + stock work</p><h1>Production calendar</h1><p className="intro">Customer orders and in-house stock runs share one schedule.</p><div className="calendar"><CalendarDay day="MON" date="31" jobs={["8:00 · #2049 Handleware","1:00 · WO-1047 Stock"]}/><CalendarDay day="TUE" date="1" jobs={["8:00 · #2050 Clear","2:30 · Clean Line 1"]}/><CalendarDay day="WED" date="2" jobs={["8:00 · #2051 Clear","1:00 · WO-1049 Stock"]}/><CalendarDay day="THU" date="3" jobs={["9:00 · #2052 Amber"]}/><CalendarDay day="FRI" date="4" jobs={["8:00 · WO-1051 Stock","1:30 · Maintenance"]}/></div><div className="legend"><span><i className="dot order-dot"/>Customer order</span><span><i className="dot stock-dot"/>Build stock</span><span><i className="dot service-dot"/>Maintenance</span></div></>}
function ItemRates({setModal}:{setModal:(m:Modal)=>void}){return <><div className="heading-row"><div><p className="eyebrow">Owner controlled</p><h1>Item rates</h1><p className="intro">Sales quotes automatically start with these approved prices.</p></div><button className="primary" onClick={()=>setModal("rate")}>+ Add item rate</button></div><article className="panel rate-table"><div className="table-head"><span>Item</span><span>Price / case</span><span>Minimum</span><span>Sales discount</span></div><RateRow item="16 oz Clear Bottle" price="$54.00" min="4 cases" discount="Up to 8%"/><RateRow item="12 oz Amber Bottle" price="$62.00" min="4 cases" discount="Up to 8%"/><RateRow item="32 oz Handleware" price="$78.00" min="2 cases" discount="Owner approval"/></article></>}
function SimpleOwner({title}:{title:string}){return <><p className="eyebrow">Owner workspace</p><h1>{title}</h1><p className="intro">A simple detailed workspace available only to the owner.</p><article className="panel simple"><button className="primary">Open detailed view</button></article></>}

function FloorView({nav,unit,setUnit,amount,setAmount,goodCount,setGoodCount,notify}:{nav:string;unit:"bottles"|"boxes";setUnit:(v:"bottles"|"boxes")=>void;amount:string;setAmount:(v:string)=>void;goodCount:number;setGoodCount:(v:number)=>void;notify:(m:string)=>void}){
  if(nav==="Pack orders")return <PackOrders notify={notify}/>;
  const add=()=>{const n=Math.max(0,Number(amount)||0)*(unit==="boxes"?250:1);setGoodCount(Math.min(6000,goodCount+n));notify(`${n.toLocaleString()} bottles added to WO-1048`)};
  return <><div className="floor-heading"><div><p className="eyebrow">Running now · Line 1</p><h1>16 oz Clear Bottle</h1><p>WO-1048 · North Point Labs · Order #2050</p></div><strong>1:42 PM</strong></div><section className="floor-job"><div className="recipe"><Fact value={goodCount.toLocaleString()} label="Good bottles made"/><Fact value="6,000" label="Bottles needed"/><Fact value="24" label="Cases to pack"/></div><div className="progress"><span style={{width:`${goodCount/60}%`}}/></div><p className="progress-copy">{Math.round(goodCount/60)}% complete · {(6000-goodCount).toLocaleString()} bottles remaining</p><div className="entry-box"><h2>Add completed production</h2><div className="segmented"><button className={unit==="boxes"?"active":""} onClick={()=>setUnit("boxes")}>Boxes of preforms</button><button className={unit==="bottles"?"active":""} onClick={()=>setUnit("bottles")}>Individual bottles</button></div><label>{unit==="boxes"?"How many boxes? (250 bottles each)":"How many good bottles?"}<input inputMode="numeric" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="primary giant" onClick={add}>Add {unit==="boxes"?(Number(amount)||0)*250:Number(amount)||0} bottles</button></div><div className="floor-actions"><button className="secondary" onClick={()=>notify("Quality check recorded and owner notified")}>Record quality check</button><button className="finish" onClick={()=>notify("Job finished — owner and both sales reps notified")}>Finish work order & notify team</button></div></section></>}
function PackOrders({notify}:{notify:(m:string)=>void}){return <><div className="floor-heading"><div><p className="eyebrow">Packing queue</p><h1>Pack customer orders</h1><p>Exact quantities and pallet instructions for each order.</p></div></div><div className="pack-grid"><PackCard id="#2051" customer="Atlas Chemical" product="16 oz Clear Bottle" cases="8 cases" bottles="2,000 bottles" pallets="1 pallet · 8 cases" status="Ready to pack" notify={notify}/><PackCard id="#2050" customer="North Point Labs" product="12 oz Amber Bottle" cases="24 cases" bottles="6,000 bottles" pallets="2 pallets · 12 cases each" status="Waiting on production" notify={notify}/></div></>}

function Kpi({label,value,note,warn}:{label:string;value:string;note?:string;warn?:boolean}){return <article className={`kpi ${warn?"warn":""}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</article>}
function MoneyRow({customer,amount,detail,danger,good}:{customer:string;amount:string;detail:string;danger?:boolean;good?:boolean}){return <div className="money-row"><span><b>{customer}</b><small>{detail}</small></span><strong className={danger?"danger":good?"paid":""}>{amount}</strong></div>}
function MiniRow({title,detail,status}:{title:string;detail:string;status:string}){return <div className="mini-row"><span><b>{title}</b><small>{detail}</small></span><em>{status}</em></div>}
function LeadRow({company,contact,owner,next}:{company:string;contact:string;owner:string;next:string}){return <button><span className="initials">{company.split(" ").map(x=>x[0]).join("")}</span><span><b>{company}</b><small>{contact}</small></span><span><b>{owner}</b><small>{next}</small></span></button>}
function OrdersTable({compact=false,embedded=false}:{compact?:boolean;embedded?:boolean}){return <div className={`orders-table ${compact?"compact":""} ${embedded?"embedded":""}`}><div className="table-head"><span>Order</span><span>Customer / items</span><span>Due</span><span>Status</span><span>Payment</span></div>{orders.map(o=><button className="order-line" key={o.id}><b>{o.id}</b><span><b>{o.customer}</b><small>{o.item}</small></span><span>{o.due}</span><em>{o.status}</em><strong className={o.money.includes("overdue")?"danger":o.money==="Paid"?"paid":""}>{o.money}</strong></button>)}</div>}
function Decision({n,name,detail}:{n:string;name:string;detail:string}){return <button className="order"><span className="initials">{n}</span><span><b>{name}</b><small>{detail}</small></span><em>Review</em></button>}
function Fact({value,label}:{value:string;label:string}){return <div className="fact"><strong>{value}</strong><span>{label}</span></div>}
function WorkRow({id,item,purpose,status}:{id:string;item:string;purpose:string;status:string}){return <button><span className="initials">{id.slice(-2)}</span><span><b>{id} · {item}</b><small>{purpose}</small></span><span>{status} →</span></button>}
function CalendarDay({day,date,jobs}:{day:string;date:string;jobs:string[]}){return <article><header><span>{day}</span><strong>{date}</strong></header>{jobs.map((j,i)=><button key={j} className={j.includes("Stock")?"stock-job":j.includes("Maintenance")||j.includes("Clean")?"service-job":"order-job"}>{j}</button>)}</article>}
function RateRow({item,price,min,discount}:{item:string;price:string;min:string;discount:string}){return <button><b>{item}</b><strong>{price}</strong><span>{min}</span><span>{discount}</span></button>}
function PackCard({id,customer,product,cases,bottles,pallets,status,notify}:{id:string;customer:string;product:string;cases:string;bottles:string;pallets:string;status:string;notify:(m:string)=>void}){return <article className="pack-card"><p className="eyebrow">Order {id}</p><h2>{customer}</h2><p>{product}</p><div className="pack-facts"><Fact value={cases} label="Total to pack"/><Fact value={bottles} label="Bottle quantity"/><Fact value={pallets} label="Pallet plan"/></div><div className="pack-status">{status}</div><button className="primary giant" onClick={()=>notify(`${id} packed — owner and sales reps notified`)}>Mark packed & notify team</button></article>}

function ActionModal({type,close,complete}:{type:Exclude<Modal,null>;close:()=>void;complete:(m:string)=>void}){
  const title={quote:"Create quote",invoice:"Create invoice",lead:"Add shared lead",import:"Import customers from CSV",workorder:"Create work order",rate:"Set item rate"}[type];
  return <div className="overlay" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="modal wide-modal" role="dialog" aria-modal="true"><button className="close" onClick={close}>×</button><p className="eyebrow">Guided setup</p><h2>{title}</h2>{type==="quote"||type==="invoice"?<><div className="form-grid"><label>Customer<select><option>Martin Supply</option><option>North Point Labs</option></select></label><label>Item<select><option>16 oz Clear · $54/case</option><option>12 oz Amber · $62/case</option></select></label><label>Cases<input defaultValue="12"/></label><label>Discount<input defaultValue="5%"/></label><label>Shipping rate<input defaultValue="$180.00"/></label><label>Payment terms<select><option>Net 30</option><option>Due on receipt</option></select></label></div><div className="quote-total"><span>Owner rate + shipping − discount</span><strong>$3,258.00</strong></div></>:type==="import"?<><div className="upload-zone"><strong>Choose a CSV customer file</strong><span>Company, contact, phone, email, address</span><button className="secondary">Choose file</button></div><p className="hint">You’ll preview and match columns before anything is added.</p></>:type==="workorder"?<div className="form-grid"><label>Purpose<select><option>Build in-house stock</option><option>Customer order</option></select></label><label>Bottle<select><option>16 oz Clear Bottle</option><option>12 oz Amber Bottle</option></select></label><label>Quantity<input defaultValue="4,000"/></label><label>Schedule<input type="date" defaultValue="2026-09-04"/></label></div>:type==="rate"?<div className="form-grid"><label>Item<input defaultValue="24 oz Clear Bottle"/></label><label>Price per case<input defaultValue="$68.00"/></label><label>Minimum order<input defaultValue="4 cases"/></label><label>Rep discount limit<input defaultValue="8%"/></label></div>:<div className="form-grid"><label>Company<input placeholder="Company name"/></label><label>Contact<input placeholder="Contact name"/></label><label>Phone<input placeholder="Phone"/></label><label>Assigned rep<select><option>Unassigned</option><option>Dad</option><option>Sarah</option></select></label></div>}<button className="primary full" onClick={()=>complete(`${title} saved`)}>{type==="import"?"Preview import":type==="quote"?"Save quote":type==="workorder"?"Create & schedule":"Save"}</button><button className="cancel" onClick={close}>Cancel</button></section></div>
}
function Toast({text}:{text:string}){return <div className="toast">✓ {text}</div>}
